(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Import Coq.Strings.String.

Open Scope Z_scope.
Module C.

Record State : Set := state
{ str : bytestring
}.

Definition C (ENV : Env)  :=
state (to_bytestring "Hello world!")
.

Definition upd0 (ENV : Env) (STATE : State)  :=
state (to_bytestring "Hello world, again!")
.

Inductive reachable  : State -> State -> Prop :=
| C_base : forall (ENV : Env) ,
     reachable (C ENV ) (C ENV )

| upd0_step : forall (ENV : Env) (BASE STATE : State) ,
     reachable BASE STATE
  -> True
  -> reachable BASE (upd0 ENV STATE )

.

End C.
