(* --- GENERATED BY ACT --- *)

Require Import Stdlib.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Stdlib.Strings.String.

Module Str := Stdlib.Strings.String.
Open Scope Z_scope.

Module Token.

Record State : Set := state
{ addr : address
; BALANCE : Z
; allowance : address -> address -> Z
; balanceOf : address -> Z
; totalSupply : Z
}.

Inductive addressIn (STATE : State) : address -> Prop :=
| addressOf_This :
     addressIn STATE (addr STATE)

.

Inductive noAliasing (STATE : State) : Prop :=
| noAliasingC :
     noAliasing STATE

.

Inductive stateIntegerBounds (STATE : State) : Prop :=
| integerBoundsC :
     0 <= Token.addr STATE <= UINT_MAX 160
  -> 0 <= BALANCE STATE <= UINT_MAX 256
  -> (forall i0 i1, 0 <= allowance STATE i0 i1 <= UINT_MAX 256)
  -> (forall i0, 0 <= balanceOf STATE i0 <= UINT_MAX 256)
  -> 0 <= totalSupply STATE <= UINT_MAX 256
  -> stateIntegerBounds STATE

.

Definition nextAddrConstraint (NextAddr : address) (STATE : State) :=
  forall (p : address), addressIn STATE p -> NextAddr > p
.

Inductive constructor_conds (ENV : Env) (_totalSupply : Z) (NextAddr : address) : Prop :=
| constructor_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_argConstraints_intBounds__totalSupply : 0 <= _totalSupply <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_This_eq_NextAddr : This ENV = NextAddr ),
  constructor_conds ENV _totalSupply NextAddr

.

Inductive constructor (ENV : Env) (_totalSupply : Z) (NextAddr : address) : State -> address -> Prop :=
| Token_case0 : forall NextAddr1
  ( H_conds : constructor_conds ENV _totalSupply NextAddr )
  ( H_case_cond : True )
  ( H_bindings0 : NextAddr1 = NextAddr + 1 ),
  constructor ENV _totalSupply NextAddr (state NextAddr 0 (fun _binding_0 => (fun _ => 0)) (fun _binding_0 => if ((_binding_0) =? (Caller ENV))%bool then _totalSupply else 0) _totalSupply) (NextAddr1)

.

Inductive init STATE : Prop :=
| fromConstructor : forall (ENV : Env) (_totalSupply : Z) (NextAddr : address) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  -> init STATE

.

Inductive initBefore (BOUND : address) STATE : Prop :=
| fromConstructorBefore : forall (ENV : Env) (_totalSupply : Z) (NextAddr : address) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  -> NextAddr' <= BOUND
  -> initBefore BOUND STATE

.



Inductive transfer_conds (ENV : Env) (_value : Z) (to : address) (STATE : State) (NextAddr : address) : Prop :=
| transfer_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 <= ((Token.balanceOf STATE) (Caller ENV))) /\ (((Token.balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= _value) /\ (_value <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf STATE) (Caller ENV)) - _value)) /\ ((((Token.balanceOf STATE) (Caller ENV)) - _value) <= (UINT_MAX 256))))) )
  ( H_iff2 : (((Caller ENV) <> to) -> (((0 <= ((Token.balanceOf STATE) to)) /\ (((Token.balanceOf STATE) to) <= (UINT_MAX 256))) /\ (((0 <= _value) /\ (_value <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf STATE) to) + _value)) /\ ((((Token.balanceOf STATE) to) + _value) <= (UINT_MAX 256)))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds__value : 0 <= _value <= UINT_MAX 256 )
  ( H_argConstraints_intBounds_to : 0 <= to <= UINT_MAX 160 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  transfer_conds ENV _value to STATE NextAddr

.

Inductive transfer_transition (ENV : Env) (_value : Z) (to : address) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| transfer_case0 : forall
  ( H_conds : transfer_conds ENV _value to STATE NextAddr )
  ( H_case_cond : ((Caller ENV) <> to) ),
  transfer_transition ENV _value to STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? (Caller ENV))%bool then (((Token.balanceOf STATE) (Caller ENV)) - _value) else if ((_binding_0) =? to)%bool then (((Token.balanceOf STATE) to) + _value) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transfer_case1 : forall
  ( H_conds : transfer_conds ENV _value to STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = to) ),
  transfer_transition ENV _value to STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive transfer_ret (ENV : Env) (_value : Z) (to : address) (STATE : State) (NextAddr : address) : bool -> Prop :=
| transfer_case0_ret :
     transfer_conds ENV _value to STATE NextAddr
  -> ((Caller ENV) <> to)
  -> transfer_ret ENV _value to STATE NextAddr true

| transfer_case1_ret :
     transfer_conds ENV _value to STATE NextAddr
  -> ((Caller ENV) = to)
  -> transfer_ret ENV _value to STATE NextAddr true

.


Inductive transferFrom_conds (ENV : Env) (src : address) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : Prop :=
| transferFrom_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (amount <= ((Token.balanceOf STATE) src)) )
  ( H_iff2 : ((src <> dst) -> (((0 <= ((Token.balanceOf STATE) dst)) /\ (((Token.balanceOf STATE) dst) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf STATE) dst) + amount)) /\ ((((Token.balanceOf STATE) dst) + amount) <= (UINT_MAX 256)))))) )
  ( H_iff3 : (((Caller ENV) <> src) -> (((0 <= (((Token.allowance STATE) src) (Caller ENV))) /\ ((((Token.allowance STATE) src) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= ((((Token.allowance STATE) src) (Caller ENV)) - amount)) /\ (((((Token.allowance STATE) src) (Caller ENV)) - amount) <= (UINT_MAX 256)))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_src : 0 <= src <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_dst : 0 <= dst <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 <= amount <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  transferFrom_conds ENV src dst amount STATE NextAddr

.

Inductive transferFrom_transition (ENV : Env) (src : address) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| transferFrom_case0 : forall
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : ((src <> dst) /\ ((Caller ENV) = src)) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) =? dst)%bool then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case1 : forall
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src <> dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) =? dst)%bool then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case2 : forall
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src <> dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (fun _binding_1 => if ((_binding_1) =? (Caller ENV))%bool then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) =? dst)%bool then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case3 : forall
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src = dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (fun _binding_1 => if ((_binding_1) =? (Caller ENV))%bool then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case4 : forall
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : ((src = dst) /\ (((Caller ENV) = src) \/ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive transferFrom_ret (ENV : Env) (src : address) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : bool -> Prop :=
| transferFrom_case0_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  -> ((src <> dst) /\ ((Caller ENV) = src))
  -> transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case1_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))
  -> transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case2_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  -> transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case3_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  -> (((src = dst) /\ ((Caller ENV) <> src)) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  -> transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case4_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  -> ((src = dst) /\ (((Caller ENV) = src) \/ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))))
  -> transferFrom_ret ENV src dst amount STATE NextAddr true

.


Inductive approve_conds (ENV : Env) (spender : address) (amount : Z) (STATE : State) (NextAddr : address) : Prop :=
| approve_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : ((0 <= amount) /\ (amount <= (UINT_MAX 256))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_spender : 0 <= spender <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 <= amount <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  approve_conds ENV spender amount STATE NextAddr

.

Inductive approve_transition (ENV : Env) (spender : address) (amount : Z) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| approve_case0 : forall
  ( H_conds : approve_conds ENV spender amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) <> spender) ),
  approve_transition ENV spender amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) =? (Caller ENV))%bool then (fun _binding_1 => if ((_binding_1) =? spender)%bool then amount else ((Token.allowance STATE) (Caller ENV))_binding_1) else (Token.allowance STATE)_binding_0) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

| approve_case1 : forall
  ( H_conds : approve_conds ENV spender amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = spender) ),
  approve_transition ENV spender amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive approve_ret (ENV : Env) (spender : address) (amount : Z) (STATE : State) (NextAddr : address) : bool -> Prop :=
| approve_case0_ret :
     approve_conds ENV spender amount STATE NextAddr
  -> ((Caller ENV) <> spender)
  -> approve_ret ENV spender amount STATE NextAddr true

| approve_case1_ret :
     approve_conds ENV spender amount STATE NextAddr
  -> ((Caller ENV) = spender)
  -> approve_ret ENV spender amount STATE NextAddr true

.


Inductive burn_conds (ENV : Env) (amount : Z) (STATE : State) (NextAddr : address) : Prop :=
| burn_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 <= (Token.totalSupply STATE)) /\ ((Token.totalSupply STATE) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= ((Token.totalSupply STATE) - amount)) /\ (((Token.totalSupply STATE) - amount) <= (UINT_MAX 256))))) )
  ( H_iff2 : (((0 <= ((Token.balanceOf STATE) (Caller ENV))) /\ (((Token.balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf STATE) (Caller ENV)) - amount)) /\ ((((Token.balanceOf STATE) (Caller ENV)) - amount) <= (UINT_MAX 256))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_amount : 0 <= amount <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  burn_conds ENV amount STATE NextAddr

.

Inductive burn_transition (ENV : Env) (amount : Z) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| burn_case0 : forall
  ( H_conds : burn_conds ENV amount STATE NextAddr )
  ( H_case_cond : True ),
  burn_transition ENV amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? (Caller ENV))%bool then (((Token.balanceOf STATE) (Caller ENV)) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

.

Inductive burn_ret (ENV : Env) (amount : Z) (STATE : State) (NextAddr : address) : bool -> Prop :=
| burn_case0_ret :
     burn_conds ENV amount STATE NextAddr
  -> True
  -> burn_ret ENV amount STATE NextAddr true

.


Inductive burnFrom_conds (ENV : Env) (src : address) (amount : Z) (STATE : State) (NextAddr : address) : Prop :=
| burnFrom_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (amount <= (Token.totalSupply STATE)) )
  ( H_iff2 : (amount <= ((Token.balanceOf STATE) src)) )
  ( H_iff3 : (((Caller ENV) <> src) -> (amount <= (((Token.allowance STATE) src) (Caller ENV)))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_src : 0 <= src <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 <= amount <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  burnFrom_conds ENV src amount STATE NextAddr

.

Inductive burnFrom_transition (ENV : Env) (src : address) (amount : Z) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| burnFrom_case0 : forall
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : (((Caller ENV) <> src) /\ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

| burnFrom_case1 : forall
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : (((Caller ENV) <> src) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (fun _binding_1 => if ((_binding_1) =? (Caller ENV))%bool then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

| burnFrom_case2 : forall
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = src) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? src)%bool then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

.

Inductive burnFrom_ret (ENV : Env) (src : address) (amount : Z) (STATE : State) (NextAddr : address) : bool -> Prop :=
| burnFrom_case0_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  -> (((Caller ENV) <> src) /\ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))
  -> burnFrom_ret ENV src amount STATE NextAddr true

| burnFrom_case1_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  -> (((Caller ENV) <> src) /\ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  -> burnFrom_ret ENV src amount STATE NextAddr true

| burnFrom_case2_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  -> ((Caller ENV) = src)
  -> burnFrom_ret ENV src amount STATE NextAddr true

.


Inductive mint_conds (ENV : Env) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : Prop :=
| mint_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 <= (Token.totalSupply STATE)) /\ ((Token.totalSupply STATE) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= ((Token.totalSupply STATE) + amount)) /\ (((Token.totalSupply STATE) + amount) <= (UINT_MAX 256))))) )
  ( H_iff2 : (((0 <= ((Token.balanceOf STATE) dst)) /\ (((Token.balanceOf STATE) dst) <= (UINT_MAX 256))) /\ (((0 <= amount) /\ (amount <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf STATE) dst) + amount)) /\ ((((Token.balanceOf STATE) dst) + amount) <= (UINT_MAX 256))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_dst : 0 <= dst <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 <= amount <= UINT_MAX 256 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  mint_conds ENV dst amount STATE NextAddr

.

Inductive mint_transition (ENV : Env) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| mint_case0 : forall
  ( H_conds : mint_conds ENV dst amount STATE NextAddr )
  ( H_case_cond : True ),
  mint_transition ENV dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) =? dst)%bool then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) + amount)) (NextAddr)

.

Inductive mint_ret (ENV : Env) (dst : address) (amount : Z) (STATE : State) (NextAddr : address) : bool -> Prop :=
| mint_case0_ret :
     mint_conds ENV dst amount STATE NextAddr
  -> True
  -> mint_ret ENV dst amount STATE NextAddr true

.


Inductive totalSupply_conds (ENV : Env) (STATE : State) (NextAddr : address) : Prop :=
| totalSupply_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  totalSupply_conds ENV STATE NextAddr

.

Inductive totalSupply_transition (ENV : Env) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| totalSupply_case0 : forall
  ( H_conds : totalSupply_conds ENV STATE NextAddr )
  ( H_case_cond : True ),
  totalSupply_transition ENV STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive totalSupply_ret (ENV : Env) (STATE : State) (NextAddr : address) : Z -> Prop :=
| totalSupply_case0_ret :
     totalSupply_conds ENV STATE NextAddr
  -> True
  -> totalSupply_ret ENV STATE NextAddr (Token.totalSupply STATE)

.


Inductive balanceOf_conds (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : Prop :=
| balanceOf_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_idx : 0 <= idx <= UINT_MAX 160 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  balanceOf_conds ENV idx STATE NextAddr

.

Inductive balanceOf_transition (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| balanceOf_case0 : forall
  ( H_conds : balanceOf_conds ENV idx STATE NextAddr )
  ( H_case_cond : True ),
  balanceOf_transition ENV idx STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive balanceOf_ret (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : Z -> Prop :=
| balanceOf_case0_ret :
     balanceOf_conds ENV idx STATE NextAddr
  -> True
  -> balanceOf_ret ENV idx STATE NextAddr ((Token.balanceOf STATE) idx)

.


Inductive allowance_conds (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : Prop :=
| allowance_condsC : forall
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_idx1 : 0 <= idx1 <= UINT_MAX 160 )
  ( H_argConstraints_intBounds_idx2 : 0 <= idx2 <= UINT_MAX 160 )
  ( H_CallerBound : 0 <= Caller ENV <= UINT_MAX 160 )
  ( H_OriginBound : 0 <= Origin ENV <= UINT_MAX 160 )
  ( H_ThisBound : 0 <= This ENV <= UINT_MAX 160 )
  ( H_NextAddressBound : 0 <= NextAddr <= UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (forall (p : address), addressIn STATE p -> Caller ENV <> p) )
  ( H_no_self_origin : (forall (p : address), addressIn STATE p -> Origin ENV <> p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  allowance_conds ENV idx1 idx2 STATE NextAddr

.

Inductive allowance_transition (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : State -> address -> Prop :=
| allowance_case0 : forall
  ( H_conds : allowance_conds ENV idx1 idx2 STATE NextAddr )
  ( H_case_cond : True ),
  allowance_transition ENV idx1 idx2 STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

.

Inductive allowance_ret (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : Z -> Prop :=
| allowance_case0_ret :
     allowance_conds ENV idx1 idx2 STATE NextAddr
  -> True
  -> allowance_ret ENV idx1 idx2 STATE NextAddr (((Token.allowance STATE) idx1) idx2)

.


Inductive Token_transition (ENV : Env) (STATE : State) (NextAddr : address) (STATE' : State) (NextAddr' : address) : Prop :=
| transfer_Token_transition : forall (_value : Z) (to : address),
   transfer_transition ENV _value to STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| transferFrom_Token_transition : forall (src : address) (dst : address) (amount : Z),
   transferFrom_transition ENV src dst amount STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| approve_Token_transition : forall (spender : address) (amount : Z),
   approve_transition ENV spender amount STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| burn_Token_transition : forall (amount : Z),
   burn_transition ENV amount STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| burnFrom_Token_transition : forall (src : address) (amount : Z),
   burnFrom_transition ENV src amount STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| mint_Token_transition : forall (dst : address) (amount : Z),
   mint_transition ENV dst amount STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| totalSupply_Token_transition :
   totalSupply_transition ENV STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| balanceOf_Token_transition : forall (idx : address),
   balanceOf_transition ENV idx STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
| allowance_Token_transition : forall (idx1 : address) (idx2 : address),
   allowance_transition ENV idx1 idx2 STATE NextAddr STATE' NextAddr'
-> Token_transition ENV STATE NextAddr STATE' NextAddr'
.

Inductive transition (ENV : Env) (STATE : State) (NextAddr : address) (STATE' : State) (NextAddr' : address) : Prop :=
| transition_Token :
     Token_transition ENV STATE NextAddr STATE' NextAddr'
  -> transition ENV STATE NextAddr STATE' NextAddr'

.

Definition step (STATE : State) (STATE' : State) :=
exists (ENV : Env) (NextAddr : address) (NextAddr' : address), transition ENV STATE NextAddr STATE' NextAddr'.

Definition multistep (STATE STATE' : State) :=
multistep step STATE STATE'.

Definition reachable (STATE : State) :=
exists STATE', init STATE' /\ multistep STATE' STATE.

Definition reachableFromInit (ENV : Env) (_totalSupply : Z) (NextAddr : address) (STATE : State) :=
exists STATE' NextAddr', constructor ENV _totalSupply NextAddr STATE' NextAddr' /\ multistep STATE' STATE.

Definition stepBefore (BOUND : address) (STATE : State) (STATE' : State) :=
exists (ENV : Env) (NextAddr : address) (NextAddr' : address), transition ENV STATE NextAddr STATE' NextAddr' /\ NextAddr' <= BOUND.

Definition multistepBefore (BOUND : address) (STATE : State) (STATE' : State) :=
ActLib.multistep (stepBefore BOUND) STATE STATE'.

Definition reachableBefore (BOUND : address) (STATE : State) :=
exists STATE', initBefore BOUND STATE' /\ multistepBefore BOUND STATE' STATE.

Definition burnFrom_post0 :=
  forall (NextAddr : address) (NextAddr' : address) (ENV : Env) (STATE : State) (STATE' : State) (src : address) (amount : Z),
     burnFrom_conds ENV src amount STATE NextAddr
  -> reachable STATE
  -> burnFrom_transition ENV src amount STATE NextAddr STATE' NextAddr'
  -> ((((Token.balanceOf STATE) src) - ((Token.balanceOf STATE') src)) = ((Token.totalSupply STATE) - (Token.totalSupply STATE')))
.

Definition invariantInit (IP : Env -> Z -> address -> State -> Prop) :=
  forall (ENV : Env) (_totalSupply : Z) (NextAddr : address) (STATE : State) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  -> IP ENV _totalSupply NextAddr STATE
.

Definition invariantStep (IP : Env -> Z -> address -> State -> Prop) :=
  forall (ENV : Env) (_totalSupply : Z) (NextAddr : address) (STATE : State) (STATE' : State),
     constructor_conds ENV _totalSupply NextAddr
  -> step STATE STATE'
  -> IP ENV _totalSupply NextAddr STATE
  -> IP ENV _totalSupply NextAddr STATE'
.

Lemma invariantReachable :
  forall (ENV : Env) (_totalSupply : Z) (NextAddr : address) (STATE : State) (IP : Env -> Z -> address -> State -> Prop) (HIPinvInit : invariantInit IP) (HIPinvStep : invariantStep IP),
     reachableFromInit ENV _totalSupply NextAddr (STATE : State)
  -> IP ENV _totalSupply NextAddr STATE
.
Proof.
  intros ENV _totalSupply NextAddr STATE IP HIPinvInit HIPinvStep Hreach.
  unfold reachableFromInit in Hreach.
  destruct Hreach as [iState [iNA [Hinit Hmulti]]].
  apply step_multi_step with (P := fun s s' => IP ENV _totalSupply NextAddr s -> IP ENV _totalSupply NextAddr s' ) in Hmulti.
  - apply Hmulti.
    eapply HIPinvInit; eassumption.
  - intros s s' Hstep.
    destruct Hinit as [iNA' Hprecs].
    eapply HIPinvStep with (STATE := s) (STATE' := s'); eassumption.
  - unfold Relation_Definitions.reflexive.
    intros.
    assumption.
  - unfold Relation_Definitions.transitive.
    intros s1 s2 s3 Ht1 Ht2 Ht3.
    apply Ht2, Ht1.
    assumption.

Qed.


End Token.
