(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module Token.

Record State : Set := state
{ allowance : address -> address -> Z
; balanceOf : address -> Z
; totalSupply : Z
}.

Definition Token (ENV : Env) (_totalSupply : Z) :=
state (fun _binding_0 _binding_1 => ((fun _ _ => 0) _binding_0 _binding_1)) (fun _binding_0 => if ((_binding_0 =? (Caller ENV)))%bool then _totalSupply else ((fun _ => 0) _binding_0)) _totalSupply
.

Definition transfer0 (ENV : Env) (STATE : State) (value : Z) (to : address) :=
state (fun _binding_0 _binding_1 => ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => if ((_binding_0 =? to))%bool then (((balanceOf STATE) to) + value) else if ((_binding_0 =? (Caller ENV)))%bool then (((balanceOf STATE) (Caller ENV)) - value) else ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Definition transfer1 (ENV : Env) (STATE : State) (value : Z) (to : address) :=
state (fun _binding_0 _binding_1 => ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Definition transferFrom0 (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) :=
state (fun _binding_0 _binding_1 => ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => if ((_binding_0 =? dst))%bool then (((balanceOf STATE) dst) + amount) else if ((_binding_0 =? src))%bool then (((balanceOf STATE) src) - amount) else ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Definition transferFrom1 (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) :=
state (fun _binding_0 _binding_1 => ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => if ((_binding_0 =? dst))%bool then (((balanceOf STATE) dst) + amount) else if ((_binding_0 =? src))%bool then (((balanceOf STATE) src) - amount) else ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Definition transferFrom2 (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) :=
state (fun _binding_0 _binding_1 => if ((_binding_0 =? src) && (_binding_1 =? (Caller ENV)))%bool then (((allowance STATE) src (Caller ENV)) - amount) else ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => if ((_binding_0 =? dst))%bool then (((balanceOf STATE) dst) + amount) else if ((_binding_0 =? src))%bool then (((balanceOf STATE) src) - amount) else ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Definition transferFrom3 (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) :=
state (fun _binding_0 _binding_1 => ((allowance STATE) _binding_0 _binding_1)) (fun _binding_0 => ((balanceOf STATE) _binding_0)) (totalSupply STATE)
.

Inductive transfer0_ret (ENV : Env) (STATE : State) (value : Z) (to : address) : Z -> Prop :=
| transfer0_ret_intro :
     ((Callvalue ENV) = 0)
  -> (value <= ((balanceOf STATE) (Caller ENV)))
  -> (((Caller ENV) <> to) -> ((((balanceOf STATE) to) + value) < (2 ^ 256)))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) <> to)
  -> transfer0_ret ENV STATE value to 1

.

Inductive transfer1_ret (ENV : Env) (STATE : State) (value : Z) (to : address) : Z -> Prop :=
| transfer1_ret_intro :
     ((Callvalue ENV) = 0)
  -> (value <= ((balanceOf STATE) (Caller ENV)))
  -> (((Caller ENV) <> to) -> ((((balanceOf STATE) to) + value) < (2 ^ 256)))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) = to)
  -> transfer1_ret ENV STATE value to 1

.

Inductive transferFrom0_ret (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) : Z -> Prop :=
| transferFrom0_ret_intro :
     (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((src <> dst) /\ ((Caller ENV) = src))
  -> transferFrom0_ret ENV STATE src dst amount 1

.

Inductive transferFrom1_ret (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) : Z -> Prop :=
| transferFrom1_ret_intro :
     (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ (((allowance STATE) src (Caller ENV)) = ((2 ^ 256) - 1)))
  -> transferFrom1_ret ENV STATE src dst amount 1

.

Inductive transferFrom2_ret (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) : Z -> Prop :=
| transferFrom2_ret_intro :
     (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ (((allowance STATE) src (Caller ENV)) < ((2 ^ 256) - 1)))
  -> transferFrom2_ret ENV STATE src dst amount 1

.

Inductive transferFrom3_ret (ENV : Env) (STATE : State) (src : address) (dst : address) (amount : Z) : Z -> Prop :=
| transferFrom3_ret_intro :
     (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> (src = dst)
  -> transferFrom3_ret ENV STATE src dst amount 1

.

Inductive reachable  : State -> State -> Prop :=
| Token_base : forall (ENV : Env) (_totalSupply : Z),
     ((0 <= _totalSupply) /\ (_totalSupply <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable (Token ENV _totalSupply) (Token ENV _totalSupply)

| transfer0_step : forall (ENV : Env) (BASE STATE : State) (value : Z) (to : address),
     reachable BASE STATE
  -> ((Caller ENV) <> to)
  -> ((Callvalue ENV) = 0)
  -> (value <= ((balanceOf STATE) (Caller ENV)))
  -> (((Caller ENV) <> to) -> ((((balanceOf STATE) to) + value) < (2 ^ 256)))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable BASE (transfer0 ENV STATE value to)

| transfer1_step : forall (ENV : Env) (BASE STATE : State) (value : Z) (to : address),
     reachable BASE STATE
  -> ((Caller ENV) = to)
  -> ((Callvalue ENV) = 0)
  -> (value <= ((balanceOf STATE) (Caller ENV)))
  -> (((Caller ENV) <> to) -> ((((balanceOf STATE) to) + value) < (2 ^ 256)))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable BASE (transfer1 ENV STATE value to)

| transferFrom0_step : forall (ENV : Env) (BASE STATE : State) (src : address) (dst : address) (amount : Z),
     reachable BASE STATE
  -> ((src <> dst) /\ ((Caller ENV) = src))
  -> (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom0 ENV STATE src dst amount)

| transferFrom1_step : forall (ENV : Env) (BASE STATE : State) (src : address) (dst : address) (amount : Z),
     reachable BASE STATE
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ (((allowance STATE) src (Caller ENV)) = ((2 ^ 256) - 1)))
  -> (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom1 ENV STATE src dst amount)

| transferFrom2_step : forall (ENV : Env) (BASE STATE : State) (src : address) (dst : address) (amount : Z),
     reachable BASE STATE
  -> (((src <> dst) /\ ((Caller ENV) <> src)) /\ (((allowance STATE) src (Caller ENV)) < ((2 ^ 256) - 1)))
  -> (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) src)) /\ (((balanceOf STATE) src) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom2 ENV STATE src dst amount)

| transferFrom3_step : forall (ENV : Env) (BASE STATE : State) (src : address) (dst : address) (amount : Z),
     reachable BASE STATE
  -> (src = dst)
  -> (amount <= ((balanceOf STATE) (Caller ENV)))
  -> ((src <> dst) -> ((((balanceOf STATE) dst) + amount) < (2 ^ 256)))
  -> (((Caller ENV) <> src) -> (0 <= (((allowance STATE) src (Caller ENV)) - amount)))
  -> ((Callvalue ENV) = 0)
  -> ((0 <= src) /\ (src <= (UINT_MAX 160)))
  -> ((0 <= dst) /\ (dst <= (UINT_MAX 160)))
  -> ((0 <= amount) /\ (amount <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) (Caller ENV))) /\ (((balanceOf STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) dst)) /\ (((balanceOf STATE) dst) <= (UINT_MAX 256)))
  -> ((0 <= ((allowance STATE) src (Caller ENV))) /\ (((allowance STATE) src (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom3 ENV STATE src dst amount)

.

End Token.
