(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module Token.

Record State : Set := state
{ balanceOf : address -> Z
}.

Definition Token (ENV : Env) (_supply : Z) :=
state (fun _binding_0 => if ((_binding_0 =? (Caller ENV)))%bool then _supply else ((fun _ => 0) _binding_0))
.

Definition balanceOf0 (ENV : Env) (STATE : State) (a : address) :=
state (fun _binding_0 => ((balanceOf STATE) _binding_0))
.

Definition transferFrom0 (ENV : Env) (STATE : State) (value : Z) (from : address) (to : address) :=
state (fun _binding_0 => if ((_binding_0 =? to))%bool then (((balanceOf STATE) to) + value) else if ((_binding_0 =? from))%bool then (((balanceOf STATE) from) - value) else ((balanceOf STATE) _binding_0))
.

Definition transferFrom1 (ENV : Env) (STATE : State) (value : Z) (from : address) (to : address) :=
state (fun _binding_0 => ((balanceOf STATE) _binding_0))
.

Inductive balanceOf0_ret (ENV : Env) (STATE : State) (a : address) : Z -> Prop :=
| balanceOf0_ret_intro :
     ((Callvalue ENV) = 0)
  -> ((0 <= a) /\ (a <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> True
  -> balanceOf0_ret ENV STATE a ((balanceOf STATE) a)

.

Inductive transferFrom0_ret (ENV : Env) (STATE : State) (value : Z) (from : address) (to : address) : Z -> Prop :=
| transferFrom0_ret_intro :
     ((Callvalue ENV) = 0)
  -> ((from <> to) -> (((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) to) + value)) /\ ((((balanceOf STATE) to) + value) <= (UINT_MAX 256))))))
  -> (((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) from) - value)) /\ ((((balanceOf STATE) from) - value) <= (UINT_MAX 256)))))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= from) /\ (from <= (UINT_MAX 160)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> (from <> to)
  -> transferFrom0_ret ENV STATE value from to 1

.

Inductive transferFrom1_ret (ENV : Env) (STATE : State) (value : Z) (from : address) (to : address) : Z -> Prop :=
| transferFrom1_ret_intro :
     ((Callvalue ENV) = 0)
  -> ((from <> to) -> (((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) to) + value)) /\ ((((balanceOf STATE) to) + value) <= (UINT_MAX 256))))))
  -> (((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) from) - value)) /\ ((((balanceOf STATE) from) - value) <= (UINT_MAX 256)))))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= from) /\ (from <= (UINT_MAX 160)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> (from = to)
  -> transferFrom1_ret ENV STATE value from to 1

.

Inductive reachable  : State -> State -> Prop :=
| Token_base : forall (ENV : Env) (_supply : Z),
     ((Callvalue ENV) = 0)
  -> ((0 <= _supply) /\ (_supply <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable (Token ENV _supply) (Token ENV _supply)

| balanceOf0_step : forall (ENV : Env) (BASE STATE : State) (a : address),
     reachable BASE STATE
  -> True
  -> ((Callvalue ENV) = 0)
  -> ((0 <= a) /\ (a <= (UINT_MAX 160)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (balanceOf0 ENV STATE a)

| transferFrom0_step : forall (ENV : Env) (BASE STATE : State) (value : Z) (from : address) (to : address),
     reachable BASE STATE
  -> (from <> to)
  -> ((Callvalue ENV) = 0)
  -> ((from <> to) -> (((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) to) + value)) /\ ((((balanceOf STATE) to) + value) <= (UINT_MAX 256))))))
  -> (((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) from) - value)) /\ ((((balanceOf STATE) from) - value) <= (UINT_MAX 256)))))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= from) /\ (from <= (UINT_MAX 160)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom0 ENV STATE value from to)

| transferFrom1_step : forall (ENV : Env) (BASE STATE : State) (value : Z) (from : address) (to : address),
     reachable BASE STATE
  -> (from = to)
  -> ((Callvalue ENV) = 0)
  -> ((from <> to) -> (((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) to) + value)) /\ ((((balanceOf STATE) to) + value) <= (UINT_MAX 256))))))
  -> (((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256))) /\ (((0 <= value) /\ (value <= (UINT_MAX 256))) /\ ((0 <= (((balanceOf STATE) from) - value)) /\ ((((balanceOf STATE) from) - value) <= (UINT_MAX 256)))))
  -> ((0 <= value) /\ (value <= (UINT_MAX 256)))
  -> ((0 <= from) /\ (from <= (UINT_MAX 160)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= ((balanceOf STATE) to)) /\ (((balanceOf STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balanceOf STATE) from)) /\ (((balanceOf STATE) from) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable BASE (transferFrom1 ENV STATE value from to)

.

End Token.


Module Amm.

Record State : Set := state
{ token0 : Token.State
; token1 : Token.State
}.

Definition Amm (ENV : Env) (amt1 : Z) (amt2 : Z) :=
state (Token.Token ENV amt1) (Token.Token ENV amt2)
.

Definition swap00 (ENV : Env) (STATE : State) (amt : Z) :=
state (Token.state (fun _binding_0 => if ((_binding_0 =? (This ENV)))%bool then (((Token.balanceOf (token0 STATE)) (This ENV)) + amt) else if ((_binding_0 =? (Caller ENV)))%bool then (((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt) else ((Token.balanceOf (token0 STATE)) _binding_0))) (Token.state (fun _binding_0 => if ((_binding_0 =? (Caller ENV)))%bool then (((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) else if ((_binding_0 =? (This ENV)))%bool then (((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) else ((Token.balanceOf (token1 STATE)) _binding_0)))
.

Definition swap01 (ENV : Env) (STATE : State) (amt : Z) :=
state (token0 STATE) (token1 STATE)
.

Definition swap10 (ENV : Env) (STATE : State) (amt : Z) :=
state (Token.state (fun _binding_0 => if ((_binding_0 =? (Caller ENV)))%bool then (((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) else if ((_binding_0 =? (This ENV)))%bool then (((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) else ((Token.balanceOf (token0 STATE)) _binding_0))) (Token.state (fun _binding_0 => if ((_binding_0 =? (This ENV)))%bool then (((Token.balanceOf (token1 STATE)) (This ENV)) + amt) else if ((_binding_0 =? (Caller ENV)))%bool then (((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt) else ((Token.balanceOf (token1 STATE)) _binding_0)))
.

Definition swap11 (ENV : Env) (STATE : State) (amt : Z) :=
state (token0 STATE) (token1 STATE)
.

Inductive swap00_ret (ENV : Env) (STATE : State) (amt : Z) : Z -> Prop :=
| swap00_ret_intro :
     ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) <> (This ENV))
  -> swap00_ret ENV STATE amt 1

.

Inductive swap01_ret (ENV : Env) (STATE : State) (amt : Z) : Z -> Prop :=
| swap01_ret_intro :
     ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) = (This ENV))
  -> swap01_ret ENV STATE amt 1

.

Inductive swap10_ret (ENV : Env) (STATE : State) (amt : Z) : Z -> Prop :=
| swap10_ret_intro :
     ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) <> (This ENV))
  -> swap10_ret ENV STATE amt 1

.

Inductive swap11_ret (ENV : Env) (STATE : State) (amt : Z) : Z -> Prop :=
| swap11_ret_intro :
     ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) = (This ENV))
  -> swap11_ret ENV STATE amt 1

.

Inductive reachable  : State -> State -> Prop :=
| Amm_base : forall (ENV : Env) (amt1 : Z) (amt2 : Z),
     ((Callvalue ENV) = 0)
  -> ((0 <= amt1) /\ (amt1 <= (UINT_MAX 256)))
  -> ((0 <= amt2) /\ (amt2 <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> reachable (Amm ENV amt1 amt2) (Amm ENV amt1 amt2)

| swap00_step : forall (ENV : Env) (BASE STATE : State) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) <> (This ENV))
  -> ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> reachable BASE (swap00 ENV STATE amt)

| swap01_step : forall (ENV : Env) (BASE STATE : State) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) = (This ENV))
  -> ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) - ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) + ((((Token.balanceOf (token1 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token0 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token0 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> reachable BASE (swap01 ENV STATE amt)

| swap10_step : forall (ENV : Env) (BASE STATE : State) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) <> (This ENV))
  -> ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> reachable BASE (swap10 ENV STATE amt)

| swap11_step : forall (ENV : Env) (BASE STATE : State) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) = (This ENV))
  -> ((Callvalue ENV) = 0)
  -> (((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt)) /\ ((((Token.balanceOf (token1 STATE)) (Caller ENV)) - amt) <= (UINT_MAX 256)))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))))))
  -> (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) - ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256)))))))))))
  -> (((Caller ENV) <> (This ENV)) -> (((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256))) /\ (((0 <= ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) /\ (((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token0 STATE)) (This ENV)) * amt)) /\ ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ (((0 <= (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)) /\ ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <= (UINT_MAX 256))) /\ (((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256))) /\ (((0 <= amt) /\ (amt <= (UINT_MAX 256))) /\ ((0 <= (((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt)))) /\ ((((Token.balanceOf (token0 STATE)) (Caller ENV)) + ((((Token.balanceOf (token0 STATE)) (This ENV)) * amt) / (((Token.balanceOf (token1 STATE)) (This ENV)) + amt))) <= (UINT_MAX 256))))))))))))
  -> ((((Token.balanceOf (token1 STATE)) (This ENV)) + amt) <> 0)
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token1 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (Caller ENV))) /\ (((Token.balanceOf (token0 STATE)) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token0 STATE)) (This ENV))) /\ (((Token.balanceOf (token0 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((Token.balanceOf (token1 STATE)) (This ENV))) /\ (((Token.balanceOf (token1 STATE)) (This ENV)) <= (UINT_MAX 256)))
  -> ((0 <= (Callvalue ENV)) /\ ((Callvalue ENV) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((0 <= (This ENV)) /\ ((This ENV) <= (UINT_MAX 160)))
  -> reachable BASE (swap11 ENV STATE amt)

.

End Amm.
