-- GENERATED BY ACT

import Mathlib.Data.Int.Basic
import ActLib.ActLib

open Int

namespace Token

structure State where
  addr : address
  BALANCE : ℤ
  allowance : address → address → ℤ
  balanceOf : address → ℤ
  totalSupply : ℤ

inductive addressIn (STATE : State) : address → Prop where
| addressOf_This :
     addressIn STATE (addr STATE)



inductive noAliasing (STATE : State) : Prop where
| noAliasingC :
     noAliasing STATE



inductive stateIntegerBounds (STATE : State) : Prop where
| integerBoundsC :
     0 ≤ Token.addr STATE ∧ Token.addr STATE ≤ UINT_MAX 160
  → 0 ≤ BALANCE STATE ∧ BALANCE STATE ≤ UINT_MAX 256
  → (∀ i0 i1, 0 ≤ allowance STATE i0 i1 ∧ allowance STATE i0 i1 ≤ UINT_MAX 256)
  → (∀ i0, 0 ≤ balanceOf STATE i0 ∧ balanceOf STATE i0 ≤ UINT_MAX 256)
  → 0 ≤ totalSupply STATE ∧ totalSupply STATE ≤ UINT_MAX 256
  → stateIntegerBounds STATE



def nextAddrConstraint (NextAddr : address) (STATE : State) :=
  ∀ (p : address), addressIn STATE p → NextAddr > p


inductive constructor_conds (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) : Prop where
| constructor_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_argConstraints_intBounds__totalSupply : 0 ≤ _totalSupply ∧ _totalSupply ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_This_eq_NextAddr : This ENV = NextAddr ),
  constructor_conds ENV _totalSupply NextAddr



inductive constructor (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) : State → address → Prop where
| Token_case0 : ∀ NextAddr1
  ( H_conds : constructor_conds ENV _totalSupply NextAddr )
  ( H_case_cond : True )
  ( H_bindings0 : NextAddr1 = NextAddr + 1 ),
  constructor ENV _totalSupply NextAddr (state NextAddr 0 (fun _binding_0 => (fun _ => 0)) (fun _binding_0 => if ((_binding_0) == (Caller ENV)) then _totalSupply else 0) _totalSupply) (NextAddr1)



inductive init STATE : Prop where
| fromConstructor : ∀ (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  → init STATE



inductive initBefore (BOUND : address) STATE : Prop where
| fromConstructorBefore : ∀ (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  → NextAddr' ≤ BOUND
  → initBefore BOUND STATE





inductive transfer_conds (ENV : Env) (_value : ℤ) (to : address) (STATE : State) (NextAddr : address) : Prop where
| transfer_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 ≤ ((Token.balanceOf STATE) (Caller ENV))) ∧ (((Token.balanceOf STATE) (Caller ENV)) ≤ (UINT_MAX 256))) ∧ (((0 ≤ _value) ∧ (_value ≤ (UINT_MAX 256))) ∧ ((0 ≤ (((Token.balanceOf STATE) (Caller ENV)) - _value)) ∧ ((((Token.balanceOf STATE) (Caller ENV)) - _value) ≤ (UINT_MAX 256))))) )
  ( H_iff2 : (((Caller ENV) ≠ to) → (((0 ≤ ((Token.balanceOf STATE) to)) ∧ (((Token.balanceOf STATE) to) ≤ (UINT_MAX 256))) ∧ (((0 ≤ _value) ∧ (_value ≤ (UINT_MAX 256))) ∧ ((0 ≤ (((Token.balanceOf STATE) to) + _value)) ∧ ((((Token.balanceOf STATE) to) + _value) ≤ (UINT_MAX 256)))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds__value : 0 ≤ _value ∧ _value ≤ UINT_MAX 256 )
  ( H_argConstraints_intBounds_to : 0 ≤ to ∧ to ≤ UINT_MAX 160 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  transfer_conds ENV _value to STATE NextAddr



inductive transfer_transition (ENV : Env) (_value : ℤ) (to : address) (STATE : State) (NextAddr : address) : State → address → Prop where
| transfer_case0 : ∀
  ( H_conds : transfer_conds ENV _value to STATE NextAddr )
  ( H_case_cond : ((Caller ENV) ≠ to) ),
  transfer_transition ENV _value to STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == (Caller ENV)) then (((Token.balanceOf STATE) (Caller ENV)) - _value) else if ((_binding_0) == to) then (((Token.balanceOf STATE) to) + _value) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transfer_case1 : ∀
  ( H_conds : transfer_conds ENV _value to STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = to) ),
  transfer_transition ENV _value to STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive transfer_ret (ENV : Env) (_value : ℤ) (to : address) (STATE : State) (NextAddr : address) : Bool → Prop where
| transfer_case0_ret :
     transfer_conds ENV _value to STATE NextAddr
  → ((Caller ENV) ≠ to)
  → transfer_ret ENV _value to STATE NextAddr true

| transfer_case1_ret :
     transfer_conds ENV _value to STATE NextAddr
  → ((Caller ENV) = to)
  → transfer_ret ENV _value to STATE NextAddr true




inductive transferFrom_conds (ENV : Env) (src : address) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Prop where
| transferFrom_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (amount ≤ ((Token.balanceOf STATE) src)) )
  ( H_iff2 : ((src ≠ dst) → (((0 ≤ ((Token.balanceOf STATE) dst)) ∧ (((Token.balanceOf STATE) dst) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ (((Token.balanceOf STATE) dst) + amount)) ∧ ((((Token.balanceOf STATE) dst) + amount) ≤ (UINT_MAX 256)))))) )
  ( H_iff3 : (((Caller ENV) ≠ src) → (((0 ≤ (((Token.allowance STATE) src) (Caller ENV))) ∧ ((((Token.allowance STATE) src) (Caller ENV)) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ ((((Token.allowance STATE) src) (Caller ENV)) - amount)) ∧ (((((Token.allowance STATE) src) (Caller ENV)) - amount) ≤ (UINT_MAX 256)))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_src : 0 ≤ src ∧ src ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_dst : 0 ≤ dst ∧ dst ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 ≤ amount ∧ amount ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  transferFrom_conds ENV src dst amount STATE NextAddr



inductive transferFrom_transition (ENV : Env) (src : address) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : State → address → Prop where
| transferFrom_case0 : ∀
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : ((src ≠ dst) ∧ ((Caller ENV) = src)) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) == dst) then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case1 : ∀
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src ≠ dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) == dst) then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case2 : ∀
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src ≠ dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) == src) then (fun _binding_1 => if ((_binding_1) == (Caller ENV)) then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else if ((_binding_0) == dst) then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case3 : ∀
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : (((src = dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) == src) then (fun _binding_1 => if ((_binding_1) == (Caller ENV)) then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

| transferFrom_case4 : ∀
  ( H_conds : transferFrom_conds ENV src dst amount STATE NextAddr )
  ( H_case_cond : ((src = dst) ∧ (((Caller ENV) = src) ∨ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))) ),
  transferFrom_transition ENV src dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive transferFrom_ret (ENV : Env) (src : address) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Bool → Prop where
| transferFrom_case0_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  → ((src ≠ dst) ∧ ((Caller ENV) = src))
  → transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case1_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  → (((src ≠ dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))
  → transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case2_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  → (((src ≠ dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  → transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case3_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  → (((src = dst) ∧ ((Caller ENV) ≠ src)) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  → transferFrom_ret ENV src dst amount STATE NextAddr true

| transferFrom_case4_ret :
     transferFrom_conds ENV src dst amount STATE NextAddr
  → ((src = dst) ∧ (((Caller ENV) = src) ∨ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))))
  → transferFrom_ret ENV src dst amount STATE NextAddr true




inductive approve_conds (ENV : Env) (spender : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Prop where
| approve_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : ((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_spender : 0 ≤ spender ∧ spender ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 ≤ amount ∧ amount ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  approve_conds ENV spender amount STATE NextAddr



inductive approve_transition (ENV : Env) (spender : address) (amount : ℤ) (STATE : State) (NextAddr : address) : State → address → Prop where
| approve_case0 : ∀
  ( H_conds : approve_conds ENV spender amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) ≠ spender) ),
  approve_transition ENV spender amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) == (Caller ENV)) then (fun _binding_1 => if ((_binding_1) == spender) then amount else ((Token.allowance STATE) (Caller ENV))_binding_1) else (Token.allowance STATE)_binding_0) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)

| approve_case1 : ∀
  ( H_conds : approve_conds ENV spender amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = spender) ),
  approve_transition ENV spender amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive approve_ret (ENV : Env) (spender : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Bool → Prop where
| approve_case0_ret :
     approve_conds ENV spender amount STATE NextAddr
  → ((Caller ENV) ≠ spender)
  → approve_ret ENV spender amount STATE NextAddr true

| approve_case1_ret :
     approve_conds ENV spender amount STATE NextAddr
  → ((Caller ENV) = spender)
  → approve_ret ENV spender amount STATE NextAddr true




inductive burn_conds (ENV : Env) (amount : ℤ) (STATE : State) (NextAddr : address) : Prop where
| burn_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 ≤ (Token.totalSupply STATE)) ∧ ((Token.totalSupply STATE) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ ((Token.totalSupply STATE) - amount)) ∧ (((Token.totalSupply STATE) - amount) ≤ (UINT_MAX 256))))) )
  ( H_iff2 : (((0 ≤ ((Token.balanceOf STATE) (Caller ENV))) ∧ (((Token.balanceOf STATE) (Caller ENV)) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ (((Token.balanceOf STATE) (Caller ENV)) - amount)) ∧ ((((Token.balanceOf STATE) (Caller ENV)) - amount) ≤ (UINT_MAX 256))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_amount : 0 ≤ amount ∧ amount ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  burn_conds ENV amount STATE NextAddr



inductive burn_transition (ENV : Env) (amount : ℤ) (STATE : State) (NextAddr : address) : State → address → Prop where
| burn_case0 : ∀
  ( H_conds : burn_conds ENV amount STATE NextAddr )
  ( H_case_cond : True ),
  burn_transition ENV amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == (Caller ENV)) then (((Token.balanceOf STATE) (Caller ENV)) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)



inductive burn_ret (ENV : Env) (amount : ℤ) (STATE : State) (NextAddr : address) : Bool → Prop where
| burn_case0_ret :
     burn_conds ENV amount STATE NextAddr
  → True
  → burn_ret ENV amount STATE NextAddr true




inductive burnFrom_conds (ENV : Env) (src : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Prop where
| burnFrom_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (amount ≤ (Token.totalSupply STATE)) )
  ( H_iff2 : (amount ≤ ((Token.balanceOf STATE) src)) )
  ( H_iff3 : (((Caller ENV) ≠ src) → (amount ≤ (((Token.allowance STATE) src) (Caller ENV)))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_src : 0 ≤ src ∧ src ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 ≤ amount ∧ amount ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  burnFrom_conds ENV src amount STATE NextAddr



inductive burnFrom_transition (ENV : Env) (src : address) (amount : ℤ) (STATE : State) (NextAddr : address) : State → address → Prop where
| burnFrom_case0 : ∀
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : (((Caller ENV) ≠ src) ∧ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256))) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

| burnFrom_case1 : ∀
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : (((Caller ENV) ≠ src) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256))) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (fun _binding_0 => if ((_binding_0) == src) then (fun _binding_1 => if ((_binding_1) == (Caller ENV)) then ((((Token.allowance STATE) src) (Caller ENV)) - amount) else ((Token.allowance STATE) src)_binding_1) else (Token.allowance STATE)_binding_0) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)

| burnFrom_case2 : ∀
  ( H_conds : burnFrom_conds ENV src amount STATE NextAddr )
  ( H_case_cond : ((Caller ENV) = src) ),
  burnFrom_transition ENV src amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == src) then (((Token.balanceOf STATE) src) - amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) - amount)) (NextAddr)



inductive burnFrom_ret (ENV : Env) (src : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Bool → Prop where
| burnFrom_case0_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  → (((Caller ENV) ≠ src) ∧ ((((Token.allowance STATE) src) (Caller ENV)) = (UINT_MAX 256)))
  → burnFrom_ret ENV src amount STATE NextAddr true

| burnFrom_case1_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  → (((Caller ENV) ≠ src) ∧ ((((Token.allowance STATE) src) (Caller ENV)) < (UINT_MAX 256)))
  → burnFrom_ret ENV src amount STATE NextAddr true

| burnFrom_case2_ret :
     burnFrom_conds ENV src amount STATE NextAddr
  → ((Caller ENV) = src)
  → burnFrom_ret ENV src amount STATE NextAddr true




inductive mint_conds (ENV : Env) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Prop where
| mint_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_iff1 : (((0 ≤ (Token.totalSupply STATE)) ∧ ((Token.totalSupply STATE) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ ((Token.totalSupply STATE) + amount)) ∧ (((Token.totalSupply STATE) + amount) ≤ (UINT_MAX 256))))) )
  ( H_iff2 : (((0 ≤ ((Token.balanceOf STATE) dst)) ∧ (((Token.balanceOf STATE) dst) ≤ (UINT_MAX 256))) ∧ (((0 ≤ amount) ∧ (amount ≤ (UINT_MAX 256))) ∧ ((0 ≤ (((Token.balanceOf STATE) dst) + amount)) ∧ ((((Token.balanceOf STATE) dst) + amount) ≤ (UINT_MAX 256))))) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_dst : 0 ≤ dst ∧ dst ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_amount : 0 ≤ amount ∧ amount ≤ UINT_MAX 256 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  mint_conds ENV dst amount STATE NextAddr



inductive mint_transition (ENV : Env) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : State → address → Prop where
| mint_case0 : ∀
  ( H_conds : mint_conds ENV dst amount STATE NextAddr )
  ( H_case_cond : True ),
  mint_transition ENV dst amount STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (fun _binding_0 => if ((_binding_0) == dst) then (((Token.balanceOf STATE) dst) + amount) else (Token.balanceOf STATE)_binding_0) ((Token.totalSupply STATE) + amount)) (NextAddr)



inductive mint_ret (ENV : Env) (dst : address) (amount : ℤ) (STATE : State) (NextAddr : address) : Bool → Prop where
| mint_case0_ret :
     mint_conds ENV dst amount STATE NextAddr
  → True
  → mint_ret ENV dst amount STATE NextAddr true




inductive totalSupply_conds (ENV : Env) (STATE : State) (NextAddr : address) : Prop where
| totalSupply_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  totalSupply_conds ENV STATE NextAddr



inductive totalSupply_transition (ENV : Env) (STATE : State) (NextAddr : address) : State → address → Prop where
| totalSupply_case0 : ∀
  ( H_conds : totalSupply_conds ENV STATE NextAddr )
  ( H_case_cond : True ),
  totalSupply_transition ENV STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive totalSupply_ret (ENV : Env) (STATE : State) (NextAddr : address) : ℤ → Prop where
| totalSupply_case0_ret :
     totalSupply_conds ENV STATE NextAddr
  → True
  → totalSupply_ret ENV STATE NextAddr (Token.totalSupply STATE)




inductive balanceOf_conds (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : Prop where
| balanceOf_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_idx : 0 ≤ idx ∧ idx ≤ UINT_MAX 160 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  balanceOf_conds ENV idx STATE NextAddr



inductive balanceOf_transition (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : State → address → Prop where
| balanceOf_case0 : ∀
  ( H_conds : balanceOf_conds ENV idx STATE NextAddr )
  ( H_case_cond : True ),
  balanceOf_transition ENV idx STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive balanceOf_ret (ENV : Env) (idx : address) (STATE : State) (NextAddr : address) : ℤ → Prop where
| balanceOf_case0_ret :
     balanceOf_conds ENV idx STATE NextAddr
  → True
  → balanceOf_ret ENV idx STATE NextAddr ((Token.balanceOf STATE) idx)




inductive allowance_conds (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : Prop where
| allowance_condsC : ∀
  ( H_iff0 : ((Callvalue ENV) = 0) )
  ( H_nextAddrCnstrnt_State : nextAddrConstraint NextAddr STATE )
  ( H_argConstraints_intBounds_idx1 : 0 ≤ idx1 ∧ idx1 ≤ UINT_MAX 160 )
  ( H_argConstraints_intBounds_idx2 : 0 ≤ idx2 ∧ idx2 ≤ UINT_MAX 160 )
  ( H_CallerBound : 0 ≤ Caller ENV ∧ Caller ENV ≤ UINT_MAX 160 )
  ( H_OriginBound : 0 ≤ Origin ENV ∧ Origin ENV ≤ UINT_MAX 160 )
  ( H_ThisBound : 0 ≤ This ENV ∧ This ENV ≤ UINT_MAX 160 )
  ( H_NextAddressBound : 0 ≤ NextAddr ∧ NextAddr ≤ UINT_MAX 160 )
  ( H_This_lt_NextAddr : This ENV < NextAddr )
  ( H_Caller_lt_NextAddr : Caller ENV < NextAddr )
  ( H_Origin_lt_NextAddr : Origin ENV < NextAddr )
  ( H_no_self_call : (∀ (p : address), addressIn STATE p → Caller ENV ≠ p) )
  ( H_no_self_origin : (∀ (p : address), addressIn STATE p → Origin ENV ≠ p) )
  ( H_This_eq_addState : This ENV = addr STATE ),
  allowance_conds ENV idx1 idx2 STATE NextAddr



inductive allowance_transition (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : State → address → Prop where
| allowance_case0 : ∀
  ( H_conds : allowance_conds ENV idx1 idx2 STATE NextAddr )
  ( H_case_cond : True ),
  allowance_transition ENV idx1 idx2 STATE NextAddr (state (Token.addr STATE) (Token.BALANCE STATE) (Token.allowance STATE) (Token.balanceOf STATE) (Token.totalSupply STATE)) (NextAddr)



inductive allowance_ret (ENV : Env) (idx1 : address) (idx2 : address) (STATE : State) (NextAddr : address) : ℤ → Prop where
| allowance_case0_ret :
     allowance_conds ENV idx1 idx2 STATE NextAddr
  → True
  → allowance_ret ENV idx1 idx2 STATE NextAddr (((Token.allowance STATE) idx1) idx2)




inductive Token_transition (ENV : Env) (STATE : State) (NextAddr : address) (STATE' : State) (NextAddr' : address) : Prop where
| transfer_Token_transition : ∀ (_value : ℤ) (to : address),
   transfer_transition ENV _value to STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| transferFrom_Token_transition : ∀ (src : address) (dst : address) (amount : ℤ),
   transferFrom_transition ENV src dst amount STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| approve_Token_transition : ∀ (spender : address) (amount : ℤ),
   approve_transition ENV spender amount STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| burn_Token_transition : ∀ (amount : ℤ),
   burn_transition ENV amount STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| burnFrom_Token_transition : ∀ (src : address) (amount : ℤ),
   burnFrom_transition ENV src amount STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| mint_Token_transition : ∀ (dst : address) (amount : ℤ),
   mint_transition ENV dst amount STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| totalSupply_Token_transition :
   totalSupply_transition ENV STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| balanceOf_Token_transition : ∀ (idx : address),
   balanceOf_transition ENV idx STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'
| allowance_Token_transition : ∀ (idx1 : address) (idx2 : address),
   allowance_transition ENV idx1 idx2 STATE NextAddr STATE' NextAddr'
→ Token_transition ENV STATE NextAddr STATE' NextAddr'


inductive transition (ENV : Env) (STATE : State) (NextAddr : address) (STATE' : State) (NextAddr' : address) : Prop where
| transition_Token :
     Token_transition ENV STATE NextAddr STATE' NextAddr'
  → transition ENV STATE NextAddr STATE' NextAddr'



def step (STATE : State) (STATE' : State) :=
∃ (ENV : Env) (NextAddr : address) (NextAddr' : address), transition ENV STATE NextAddr STATE' NextAddr'

def multistep (STATE STATE' : State) :=
multistep step STATE STATE'

def reachable (STATE : State) :=
∃ STATE', init STATE' ∧ multistep STATE' STATE

def reachableFromInit (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (STATE : State) :=
∃ STATE' NextAddr', constructor ENV _totalSupply NextAddr STATE' NextAddr' ∧ multistep STATE' STATE

def stepBefore (BOUND : address) (STATE : State) (STATE' : State) :=
∃ (ENV : Env) (NextAddr : address) (NextAddr' : address), transition ENV STATE NextAddr STATE' NextAddr' ∧ NextAddr' ≤ BOUND

def multistepBefore (BOUND : address) (STATE : State) (STATE' : State) :=
ActLib.multistep (stepBefore BOUND) STATE STATE'

def reachableBefore (BOUND : address) (STATE : State) :=
∃ STATE', initBefore BOUND STATE' ∧ multistepBefore BOUND STATE' STATE

def burnFrom_post0 :=
  ∀ (NextAddr : address) (NextAddr' : address) (ENV : Env) (STATE : State) (STATE' : State) (src : address) (amount : ℤ),
     burnFrom_conds ENV src amount STATE NextAddr
  → reachable STATE
  → burnFrom_transition ENV src amount STATE NextAddr STATE' NextAddr'
  → ((((Token.balanceOf STATE) src) - ((Token.balanceOf STATE') src)) = ((Token.totalSupply STATE) - (Token.totalSupply STATE')))


def invariantInit (IP : Env → ℤ → address → State → Prop) :=
  ∀ (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (STATE : State) (NextAddr' : address),
     constructor ENV _totalSupply NextAddr STATE NextAddr'
  → IP ENV _totalSupply NextAddr STATE


def invariantStep (IP : Env → ℤ → address → State → Prop) :=
  ∀ (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (STATE : State) (STATE' : State),
     constructor_conds ENV _totalSupply NextAddr
  → step STATE STATE'
  → IP ENV _totalSupply NextAddr STATE
  → IP ENV _totalSupply NextAddr STATE'


theorem invariantReachable :
  ∀ (ENV : Env) (_totalSupply : ℤ) (NextAddr : address) (STATE : State) (IP : Env → ℤ → address → State → Prop) (HIPinvInit : invariantInit IP) (HIPinvStep : invariantStep IP),
     reachableFromInit ENV _totalSupply NextAddr (STATE : State)
  → IP ENV _totalSupply NextAddr STATE

  := by
    sorry -- proof implementation needed



end Token
