(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module SafeMath.

Record State : Set := state
{ 
}.

Definition SafeMath (ENV : Env)  :=
state
.

Definition add0 (ENV : Env) (STATE : State) (x : Z) (y : Z) :=
state
.

Definition mul0 (ENV : Env) (STATE : State) (x : Z) (y : Z) :=
state
.

Inductive add0_ret (ENV : Env) (STATE : State) (x : Z) (y : Z) : Z -> Prop :=
| add0_ret_intro :
     ((0 <= (x + y)) /\ ((x + y) <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> True
  -> add0_ret ENV STATE x y (x + y)

.

Inductive mul0_ret (ENV : Env) (STATE : State) (x : Z) (y : Z) : Z -> Prop :=
| mul0_ret_intro :
     ((0 <= (x * y)) /\ ((x * y) <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> True
  -> mul0_ret ENV STATE x y (x * y)

.

Inductive reachable  : State -> State -> Prop :=
| SafeMath_base : forall (ENV : Env) ,
     reachable (SafeMath ENV ) (SafeMath ENV )

| add0_step : forall (ENV : Env) (BASE STATE : State) (x : Z) (y : Z),
     reachable BASE STATE
  -> True
  -> ((0 <= (x + y)) /\ ((x + y) <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> reachable BASE (add0 ENV STATE x y)

| mul0_step : forall (ENV : Env) (BASE STATE : State) (x : Z) (y : Z),
     reachable BASE STATE
  -> True
  -> ((0 <= (x * y)) /\ ((x * y) <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> ((0 <= x) /\ (x <= (UINT_MAX 256)))
  -> ((0 <= y) /\ (y <= (UINT_MAX 256)))
  -> reachable BASE (mul0 ENV STATE x y)

.

End SafeMath.
