{-
 -
 - lean backend for act
 -
 - unsupported features:
 - + bytestrings
 - + external storage
 - + casting from addresses to contract
 -
 - TODO: Replace THIS with NextAddr in constrs
 - -}

{-# Language OverloadedStrings #-}
{-# Language RecordWildCards #-}
{-# LANGUAGE GADTs #-}
{-# Language DataKinds #-}
{-# Language ViewPatterns #-}
{-# Language TupleSections #-}


module Act.Lean where

import Prelude hiding (GT, LT)

import Data.Map.Strict (Map)
import Data.Tuple.Extra
import qualified Data.Map.Strict    as M
import qualified Data.List.NonEmpty as NE
import qualified Data.Text          as T
import Data.List.Extra (snoc, unsnoc)
import Control.Monad.State
import Data.Maybe (mapMaybe, maybeToList)

import EVM.ABI
import Act.Syntax
import Act.Syntax.TypedExplicit

type Fresh = State Int

header :: T.Text
header = T.unlines
  [ "-- GENERATED BY ACT"
  , ""
  , "import Mathlib.Data.Int.Basic"
  , "import ActLib.ActLib"
  , ""
  , "open Int"
  , "open ActLib"
  , ""
  ]

-- | produce a lean representation of a specification
lean :: Act -> T.Text
lean (Act store contracts) =
  header <> (T.intercalate "\n\n" $ contractCode store <$> contracts)

contractCode :: StorageTyping -> Contract -> T.Text
contractCode store (Contract _ ctor@Constructor{..} behvs) = T.unlines $
  [ "namespace " <> T.pack _cname <> "\n" ]
  <> [ stateRecord ]
  <> [ contractAddressIn _cname store ]
  <> [ noAliasing _cname store ]
  <> [ intBoundsRec _cname store ]
  <> [ nextAddrConstraint ]
  <> [ constructorCode store ctor ]
  <> ( behaviourCode store <$> behvs )
  <> [ localStep _cname behvs]
  <> [ extStep _cname store ]
  <> [ step ]
  <> [ multistep ]
  <> [ reachable ]
  <> [ reachableFromInit ctor]
  <> [ stepBefore ]
  <> [ multistepBefore ]
  <> [ reachableBefore ]
  <> ( postCondConstr ctor )
  <> ( concatMap postCondBehv behvs )
  <> [ invariantInit ctor ]
  <> [ invariantStep ctor ]
  <> [ invariantReachable ctor]
  <> [ "end " <> T.pack _cname ]
  where

    stateRecord = T.unlines
      [ "structure" <+> stateType <+> "where"
      , "  " <> T.intercalate "\n  " (addrFieldDecl : map decl (M.toList store'))
      ]

    decl (n, (s, _)) = (T.pack n) <> " : " <> valueType s

    store' = contractStore _cname store

constructorCode :: StorageTyping -> Constructor -> T.Text
constructorCode store (Constructor _ cname iface _ precs cases _ invs) = T.unlines $
  [ initPrecs iface precs ]
  <> [ construction' store cname iface cases ]
  <> [ initState iface ]
  <> [ initStateBefore iface ]
  <> [ invariants iface invs ]

-- | definition of constructor preconditions
initPrecs :: Interface -> [Exp ABoolean] -> T.Text
initPrecs i conds = inductive
  initPrecsType (envDecl <+> interface i <+> nextAddrDecl) "Prop" [(initPrecsType <> "C", "∀", body)]
  where
    body = indent 2 (
      (namedHyps . concat $
      [ nameHypothesis "iff" $ leanprop <$> conds
      , interfaceConstraints i
      , maybeToList (("CallerBound",) <$> leanbound (envVar <.> "Caller") (ValueType TAddress))
      , maybeToList (("OriginBound",) <$> leanbound (envVar <.> "Origin") (ValueType TAddress))
      , maybeToList (("ThisBound",) <$> leanbound (envVar <.> "This") (ValueType TAddress))
      , maybeToList (("NextAddressBound",) <$> leanbound ("NextAddr") (ValueType TAddress))
      , [("Caller_lt_NextAddr", envVar <.> "Caller" <+> "<" <+> nextAddrVar)]
      , [("Origin_lt_NextAddr", envVar <.> "Origin" <+> "<" <+> nextAddrVar)]
      , [("This_eq_NextAddr", envVar <.> "This" <+> "=" <+> nextAddrVar)]
      ]) <> ",\n"
      <> (initPrecsType <+> envVar <+> arguments i <+> nextAddrVar))

nameHypothesis :: T.Text -> [T.Text] -> [(T.Text, T.Text)]
nameHypothesis name hyps = uncurry go <$> zip [0..] hyps
  where
    go :: Int -> T.Text -> (T.Text, T.Text)
    go i h = (name <> (T.pack $ show i), h)

indicesList :: [T.Text] -> T.Text
indicesList is = T.intercalate " → " is

argList :: [T.Text] -> T.Text
argList = T.unwords

-- | Relation characterizing constructor calls
construction' :: StorageTyping -> Id -> Interface -> Cases [StorageUpdate] -> T.Text
construction' store name i cases = inductive
  constructorType
  (argList $ [envDecl] <> interface' i <> [nextAddrDecl])
  (indicesList [stateType, addressType, "Prop"])
  (evalSeq caseCtor cases)
  where
    caseCtor :: Ccase -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ caseCond updates) = do
      caseId <- getIncr
      let name' = T.pack name <> caseSuffix caseId
      let body = indent 2 ((namedHyps . concat $
            [ [("conds", initPrecsType <+> envVar <+> arguments i <+> nextAddrVar) ]
            , [("case_cond", leanprop caseCond) ]
            , nameHypothesis ("bindings") bindingsHyp
            ]) <> ",\n"
            <> (constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> parens s <+> parens (iNextAddr finalI)))
      pure (name', "∀" <+> bindings', body)
      where 
        (s, bindings, finalI) = stateval True store name (\_ t -> defaultVal t) updates
        bindingsHyp = snd <$> bindings
        bindings' = case concatMap fst bindings of
          [] -> ""
          l -> argList l

-- | predicate characterizing all initial (post constructor) states
initState :: Interface -> T.Text
initState i = inductive
  initStateType (stateVar) (indicesList ["Prop"]) ccase
  where
    ccase = [(T.pack "fromConstructor", "∀" <+> (argList $ [envDecl] <> interface' i <> [nextAddrDecl, nextAddrDecl']) <> ",", body)]
    body = indent 2 . implication $
      [ constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar <+> nextAddrVar'
      , initStateType <+> stateVar
      ]


-- | predicate characterizing all initial (post constructor) states
initStateBefore :: Interface -> T.Text
initStateBefore i = inductive
  initStateBeforeType (boundDecl <+> stateVar) (indicesList ["Prop"]) ccase
  where
    ccase = [(T.pack "fromConstructorBefore", "∀" <+> (argList $ [envDecl] <> interface' i <> [nextAddrDecl, nextAddrDecl']) <> ",", body)]
    body = indent 2 . implication $
      [ constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar <+> nextAddrVar'
      , (nextAddrVar' <+> "≤" <+> boundVar)
      , initStateBeforeType <+> boundVar <+> stateVar 
      ]

behaviourCode :: StorageTyping -> Behaviour -> T.Text
behaviourCode store (Behaviour _ name cname iface _ precs cases _) = T.unlines $
  [ behvConds name iface precs ]
  <> [ behvPred store name cname iface cases ]
  <> [ retVal name iface cases ]

-- | definition of behaviour-case conditions
behvConds :: Id -> Interface -> [Exp ABoolean] -> T.Text
behvConds name i conds = do
  inductive
    (T.pack name <> "_conds") (envDecl <+> interface i <+> stateDecl <+> nextAddrDecl ) "Prop" [((T.pack name <> "_condsC"), "∀", body name)]
  where
    body n = indent 2 ((namedHyps . concat $
      [ nameHypothesis "iff" $ leanprop <$> conds
      , [("nextAddrCnstrnt_State", nextAddrConstraintType <+> nextAddrVar <+> stateVar) ]
      , interfaceConstraints i
      , maybeToList (("CallerBound",) <$> leanbound (envVar <.> "Caller") (ValueType TAddress))
      , maybeToList (("OriginBound",) <$> leanbound (envVar <.> "Origin") (ValueType TAddress))
      , maybeToList (("ThisBound",) <$> leanbound (envVar <.> "This") (ValueType TAddress))
      , maybeToList (("NextAddressBound",) <$> leanbound ("NextAddr") (ValueType TAddress))
      , [("This_lt_NextAddr", envVar <.> "This" <+> "<" <+> nextAddrVar)]
      , [("Caller_lt_NextAddr", envVar <.> "Caller" <+> "<" <+> nextAddrVar)]
      , [("Origin_lt_NextAddr", envVar <.> "Origin" <+> "<" <+> nextAddrVar)]
      , [("no_self_call", parens $ "∀ (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "→" <+> envVar <.> "Caller" <+> "≠" <+> "p") ]
      , [("no_self_origin", parens $ "∀ (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "→" <+> envVar <.> "Origin" <+> "≠" <+> "p") ]
      , [("This_eq_addState", envVar <.> "This" <+> "=" <+> stateVar <.> addrField)]
      ]) <> ",\n"
      <> (T.pack n <> "_conds") <+> envVar <+> arguments i <+> stateVar <+>nextAddrVar )

behvPred :: StorageTyping -> Id -> Id -> Interface -> [Bcase] -> T.Text
behvPred store name cname i cases = inductive
  (T.pack name <> "_transition") (argList $ [envDecl] <> interface' i <> [stateDecl, nextAddrDecl])  (indicesList $ [stateType, addressType, "Prop"]) caseCtors
  where
    caseCtors = (evalSeq caseCtor cases)

    caseCtor :: Bcase -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ caseCond (updates, _)) = do
      caseId <- getIncr
      pure (T.pack name <> caseSuffix caseId, "∀" <+> bindings', caseBody caseCond)
      where 
        (s, bindings, finalI) = stateval False store cname (\r _ -> ref r) updates
        bindingsHyp = snd <$> bindings
        bindings' = case concatMap fst bindings of
          [] -> ""
          l -> argList l

        caseBody c = indent 2 ((namedHyps . concat $
          [ [("conds", (T.pack name) <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar) ]
          , [("case_cond", leanprop c) ]
          , nameHypothesis ("bindings") bindingsHyp
          ]) <> ",\n"
          <> (T.pack name <> "_transition") 
            <+> envVar
            <+> arguments i
            <+> stateVar
            <+> nextAddrVar
            <+> parens s
            <+> parens (iNextAddr finalI)
            )


-- | Inductive definition of step relation of 2 states
-- that takes into account only transitions of the current contract type
localStep :: Id -> [Behaviour] -> T.Text
localStep contract behvs = inductive
  (localStepType contract) (argList [envDecl, stateDecl, nextAddrDecl, stateDecl', nextAddrDecl']) ("Prop") (stepBehv <$> behvs)
  where
    -- | constructor for the step relation
    stepBehv :: Behaviour -> (T.Text, T.Text, T.Text)
    stepBehv (Behaviour _ name _ i _ _ _ _) = (T.pack name <> "_" <> T.pack contract <> "_transition", bindings, constructorBody)
      where
        bindings = case interface i of
          "" -> ""
          i' -> "∀" <+> i' <> ","
        constructorBody = implication
          [T.pack name <> "_transition" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar' 
          , localStepType contract <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar']

-- | Constraint on Env expressing that the NextAddr field should be greated than
-- all addresses contained in the state
nextAddrConstraint :: T.Text
nextAddrConstraint = definition
  nextAddrConstraintType (nextAddrDecl <+> stateDecl) body
    where
      body = indent 2 $ forAll (parens ("p : address")) <+>
        (addressInType <+> stateVar <+> "p" ) <+> "→" <+> (nextAddrVar <+> "> p")

-- | Inductive definition of step relation of 2 states
-- that takes into account transitions of the current contract type
-- and all transitions possible for contained contracts
extStep :: Id -> StorageTyping -> T.Text
extStep main store = inductive
  extStepType (argList [envDecl, stateDecl, nextAddrDecl, stateDecl', nextAddrDecl']) "Prop" body
    where
    body =
      (extStepType <> "_" <> T.pack main, ""
      , indent 2 $ implication [localStepType main <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar', extStepType <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar'])
      : (M.elems $ M.mapMaybeWithKey substep localStore)

    localStore = contractStore main store

    substep :: Id -> (ValueType, Integer) -> Maybe (T.Text, T.Text, T.Text)
    substep var (ValueType (TContract cid), _) = Just (extStepType <> "_" <> varp, "", body')
      where
        varp = T.pack var
        body' = indent 2 . implication . concat $
          [ [ nextAddrConstraintType <+> nextAddrVar <+> stateVar ]
          , [ parens $ "∀ (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "→" <+> envVar <.> "Origin" <+> "≠" <+> "p" ]
          , [ parens $ "∀ (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "→" <+> envVar <.> "Caller" <+> "≠" <+> "p" ]
          , [ integerBoundsType <+> stateVar ]
          , [ T.pack cid <.> extStepType <+> envVar <+> parens (stateVar <.> varp) <+> nextAddrVar <+> parens (stateVar' <.> varp) <+> nextAddrVar' ]
          , [ stateVar <.> addrField <+> "=" <+> stateVar' <.> addrField ]
          , (\var' -> parens (stateVar <.> T.pack var') <+> "=" <+> parens (stateVar' <.> T.pack var')) <$> (filter (var /=) $ M.keys localStore)
          , [ extStepType <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar' ]
          ]
    substep _ _ = Nothing

step :: T.Text
step =
  definition stepType (stateDecl <+> stateDecl') $
    "∃" <+> envDecl <+> nextAddrDecl <+> nextAddrDecl' <> "," <+> extStepType <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar' <+> nextAddrVar'

stepBefore :: T.Text
stepBefore =
  definition stepBeforeType (boundDecl <+> stateDecl <+> stateDecl') $
    "∃" <+> envDecl <+> nextAddrDecl <+> nextAddrDecl' <> "," <+> extStepType <+> envVar <+> stateVar <+> nextAddrVar <+> stateVar'<+> nextAddrVar' 
    <+> "∧" <+> nextAddrVar' <+> "≤" <+> boundVar


combine :: [a] -> [(a,a)]
combine lst = combine' lst []
  where
    combine' [] acc = concat acc
    combine' (x:xs) acc =
      let xcomb = [ (x, y) | y <- xs] in
      combine' xs (xcomb:acc)

-- | Predicate that holds if p is an address of known contract type
-- in the given state
contractAddressIn :: Id -> StorageTyping -> T.Text
contractAddressIn name store = inductive
  contractAddressInType (argList [stateDecl]) (indicesList [addressType, "Prop"]) body
  where
    body = ("addressOf_This", "", indent 5 $ contractAddressInType <+> stateVar <+> parens (stateVar <.> addrField))
           : M.elems (M.mapMaybeWithKey subCAddr localStore)

    localStore = contractStore name store

    subCAddr :: Id -> (ValueType, Integer) -> Maybe (T.Text, T.Text, T.Text)
    subCAddr var (ValueType (TContract cid), _) = Just ("addressOf_" <> varp, "∀" <+> parens ("p :" <+> addressType) <> ",", body')
      where
        varp = T.pack var
        body' = indent 2 . implication $
          [ T.pack cid <.> contractAddressInType <+> parens (stateVar <.> varp) <+> "p"
          , contractAddressInType <+> stateVar <+> "p"
          ]
    subCAddr _ _ = Nothing

slotContractName :: ValueType -> Maybe Id
slotContractName (ValueType (TContract cid)) = Just cid
slotContractName _ = Nothing

noAliasing :: Id -> StorageTyping -> T.Text
noAliasing name store = inductive
  noAliasingType stateDecl "Prop" [("noAliasingC", "", body)]
  where
    body = indent 2 . implication $
      (addressSubContractAliasing <$> storeContracts)
      <> (contractPairAliasing <$> contractPairs)
      <> (subContractAliasing <$> storeContracts)
      <> [noAliasingType <+> stateVar]

    localStore = contractStore name store
    storeContracts = M.toList $ M.mapMaybe (slotContractName . fst) localStore
    contractPairs = filter (not. uncurry (==)) $ combine storeContracts

    addressSubContractAliasing :: (Id, Id) -> T.Text
    addressSubContractAliasing (cvar, cid) =
      parens $ forAll (parens ("p : address")) <+>
        ( T.pack cid <.> contractAddressInType <+> parens (stateVar <.> T.pack cvar) <+> "p") <+> "→"
        <+> (parens (stateVar <.> addrField) <+> "≠" <+> "p")

    contractPairAliasing :: ((Id, Id), (Id, Id)) -> T.Text
    contractPairAliasing ((cvar1, cid1), (cvar2, cid2)) =
      parens $ forAll (parens ("p p' : address")) <+>
        ( T.pack cid1 <.> contractAddressInType <+> parens (stateVar <.> T.pack cvar1) <+> "p") <+> "→"
        <+> ( T.pack cid2 <.> contractAddressInType <+> parens (stateVar <.> T.pack cvar2) <+> "p'") <+> "→"
        <+> ("p" <+> "≠" <+> "p'")

    subContractAliasing :: (Id, Id) -> T.Text
    subContractAliasing (cvar, cid) = T.pack cid <.> noAliasingType <+> parens (stateVar <.> T.pack cvar)


leanbound :: T.Text -> ValueType -> Maybe T.Text
leanbound v (ValueType (TContract cid)) = pure $
  "0 ≤" <+> parens v <.> addrField <+> "∧" <+> parens v <.> addrField <+> "≤ UINT_MAX 160"
leanbound v (ValueType TAddress) = pure $
  "0 ≤" <+> v <+> "∧" <+> v <+> "≤ UINT_MAX 160"
leanbound v (ValueType (TInteger n Unsigned)) = pure $
  "0 ≤" <+> v <+> "∧" <+> v <+> "≤ UINT_MAX" <+> T.pack (show n)
leanbound v (ValueType (TInteger n Signed)) = pure $
  "INT_MIN" <+> T.pack (show n) <+> "≤" <+> v <+> "∧" <+> v <+> "≤ INT_MAX" <+> T.pack (show n)
leanbound v (ValueType t@(TMapping _ _)) = case unfoldMappingType t of
  (length -> i, ValueType TAddress) -> pure $ parens $
    "∀" <+> ixs i <> ", 0 ≤" <+> v <+> ixs i <+> "∧" <+> v <+> ixs i <+> "≤ UINT_MAX 160"
  (length -> i, ValueType (TInteger n Unsigned)) -> pure $ parens $
    "∀" <+> ixs i <> ", 0 ≤" <+> v <+> ixs i <+> "∧" <+> v <+> ixs i <+> "≤ UINT_MAX" <+> T.pack (show n)
  (length -> i, ValueType (TInteger n Signed)) -> pure $ parens $
    "∀" <+> ixs i <> ", INT_MIN" <+> T.pack (show n) <+> "≤" <+> v <+> ixs i <+> "∧" <+> v <+> ixs i <+> "≤ INT_MAX" <+> T.pack (show n)
  _ -> Nothing
  where
    ixs n = T.unwords $ T.pack . (<>) "i" . show <$> [0..(n-1)]
leanbound _ _ = Nothing

intBoundsRec :: Id -> StorageTyping -> T.Text
intBoundsRec name store = inductive
  integerBoundsType stateDecl "Prop" [("integerBoundsC", "", body)]
  where
    body = indent 2 . implication $ maybeToList (leanbound (stateVar <.> addrField) (ValueType TAddress))
                                    <> ((M.elems $ M.mapMaybeWithKey go localStore) <> [integerBoundsType <+> stateVar])

    localStore = contractStore name store

    go :: Id -> (ValueType, Integer) -> Maybe T.Text
    go v (t,_) = leanbound (stateVar <.> T.pack v) t

interfaceConstraints :: Interface -> [(T.Text, T.Text)]
interfaceConstraints i@(Interface _ decls) = concatMap go decls <> interfaceConsistency i
  where go (Arg (ContractArg _ cid) (T.pack -> v)) =
          [ ("argConstraints_nextAddr_" <> v, T.pack cid <.> nextAddrConstraintType <+> nextAddrVar <+> v)
          , ("argConstraints_reachBefore_" <> v, T.pack cid <.> reachableBeforeType <+> nextAddrVar <+> v)
          , ("argConstraints_intBounds_" <> v, T.pack cid <.> integerBoundsType <+> v) ]
        go (Arg t@(AbiArg _) v) =
          maybeToList $ fmap ("argConstraints_intBounds_" <> T.pack v,) $ leanbound (T.pack v) (argToValueType t)

interfaceConsistency :: Interface -> [(T.Text, T.Text)]
interfaceConsistency (Interface _ decls) = concatMap (uncurry consistency) contractArgPairs
  where
    contractArgs = mapMaybe contractArg decls
    contractArgPairs = combine contractArgs

    contractArg (Arg (ContractArg _ c) v) = Just (c,v)
    contractArg _ = Nothing

    consistency :: (Id, Id) -> (Id, Id) -> [(T.Text, T.Text)]
    consistency (c1, (T.pack -> a1)) (c2, (T.pack -> a2)) | c1 == c2 = 
      [ ("consistency_" <> a1 <> "_eq_" <> a2 , a1<.> addrField <+>"=" <+> a2 <.> addrField
        <+> "→" <+> a1 <+> "=" <+> a2)
      , ("consistency_" <> a1 <> "_neq_" <> a2, a1 <.> addrField <+> "≠" <+> a2 <.> addrField
        <+> "→" <+> "∀" <+> parens("p p' : " <> addressType) <> ","
        <+> T.pack c1 <.> addressInType <+> a1 <+> "p" <+> "→" <+> T.pack c2 <.> addressInType <+> a2 <+> "p'"  <+> "→" <+> "p ≠ p'")]
    consistency (c1, (T.pack -> a1)) (c2, (T.pack -> a2)) =
      [ ("consistency_" <> a1 <> "_neq_" <> a2, "∀" <+> parens("p p' : " <> addressType) <> ","
        <+> T.pack c1 <.> addressInType <+> a1 <+> "p" <+> "→" <+> T.pack c2 <.> addressInType <+> a2 <+> "p'"  <+> "→" <+> "p ≠ p'")]


-- | definition of reachable states
reachable :: T.Text
reachable = definition
  reachableType args value
  where
    args = parens $ stateVar <+> ":" <+> stateType
    value = "∃" <+> stateVar' <> "," <+> initStateType <+> stateVar'
      <+> "∧" <+> multistepType <+> stateVar' <+> stateVar

reachableBefore :: T.Text
reachableBefore = definition
  reachableBeforeType args value
  where
    args = boundDecl <+> stateDecl
    value = "∃" <+> stateVar' <> "," <+> initStateBeforeType <+> boundVar <+> stateVar' 
      <+> "∧" <+> multistepBeforeType <+> boundVar <+> stateVar' <+> stateVar

-- | specialization of generic multistep
multistep :: T.Text
multistep = definition
  multistepType args value
  where
    args = parens $ stateVar <+> stateVar' <+> ":" <+> stateType
    value = ("ActLib" <.> multistepType) <+> stepType <+> stateVar <+> stateVar'

multistepBefore :: T.Text
multistepBefore = definition
  multistepBeforeType args value
  where
    args = boundDecl <+> stateDecl <+> stateDecl'
    value = "ActLib" <.> multistepType <+> parens (stepBeforeType <+> boundVar) <+> stateVar <+> stateVar'

-- | definition of reachable states from initial constructor parameters
reachableFromInit :: Constructor -> T.Text
reachableFromInit (Constructor _ _ i _ _ _ _ _ ) = definition
  reachableFromInitType args value
  where
    args = envDecl <+> interface i <+> nextAddrDecl <+> stateDecl
    value = "∃" <+> stateVar' <+> nextAddrVar' <> "," <+> constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar' <+> nextAddrVar'
      <+> "∧" <+> multistepType <+> stateVar' <+> stateVar

transition :: StorageTyping -> Id -> Id -> Interface -> [StorageUpdate] -> T.Text
transition store name cname i rewrites =
  let (s, bindings, finalI) = stateval False store cname (\r _ -> ref r) rewrites in
  definition (T.pack name) (nextAddrDecl <+> envDecl <+> stateDecl <+> interface i)
    (foldr (\(_,b) s' -> "let" <+> b <+> "in\n" <> s') (tuple (iNextAddr finalI) s) bindings)


-- | inductive definition of a return claim
-- ignores claims that do not specify a return value
retVal :: Id -> Interface -> [Bcase] -> T.Text
retVal _ _ [] = ""
retVal _ _ ((Case _ _ (_,Nothing)):_) = ""
retVal name i cases@((Case _ _ (_, Just ret0)):_) = do
  inductive
    (T.pack name <> returnSuffix)
    (envDecl <+> interface i <+> stateDecl <+> nextAddrDecl )
    (returnType ret0 <> " → Prop")
    caseCtors
  where
    retname n = n <> returnSuffix

    caseCtors = (evalSeq caseCtor cases)

    caseCtor :: Bcase -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ _ (_, Nothing)) = error "Internal error: Case does not return"
    caseCtor (Case _ caseCond (_, Just ret)) = do
      caseId <- getIncr
      pure (T.pack name <> caseSuffix caseId <> returnSuffix, "", caseBody)
      where 
        caseBody = (indent 2) . implication . concat $
          [ [(T.pack name) <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar ]
          , [ leanprop caseCond ]
          , [retname (T.pack name) <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar <+> typedexp ret]
          ]

-- | Definition of postcondition claim for constructor
postCondConstr :: Constructor -> [T.Text]
postCondConstr (Constructor _ cname iface _ _ _ postcs _) = evalSeq (go cname iface) postcs
  where
  go :: Id -> Interface -> Exp ABoolean -> Fresh T.Text
  go name i postc = do
    postName <- fresh (name <> "_post")
    pure $ definition postName "" body
    where
      body = indent 2 $ T.unlines
        [ forAll $ nextAddrDecl <+> envDecl <+> stateDecl' <+> interface i
        , implication . concat $
          [ [initPrecsType <+> nextAddrVar <+> envVar <+> arguments i]
          , [stateVar' <+> "=" <+> "snd" <+> parens (T.pack name <+> nextAddrVar <+> envVar <+> arguments i)]
          , [leanprop postc]
          ]
        ]

-- | Definition of postcondition claim for behaviour cases
postCondBehv :: Behaviour -> [T.Text]
postCondBehv (Behaviour _ bname _ iface _ _ _ postcs) = evalSeq (go bname iface) postcs
  where
  go :: Id -> Interface -> Exp ABoolean -> Fresh T.Text
  go name i postc = do
    postName <- fresh (name <> "_post")
    pure $ definition postName "" body
    where
      body = indent 2 $ T.unlines
        [ forAll $ nextAddrDecl <+> nextAddrDecl' <+> envDecl <+> stateDecl <+> stateDecl' <+> interface i
        , implication . concat $
          [ [T.pack bname <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar ]
          , [reachableType <+> stateVar]
          , [(T.pack bname <> "_transition" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar <+> stateVar'<+> nextAddrVar' )]
          , [leanprop postc]
          ]
        ]

-- | Definition of invariant proposition
invariants :: Interface -> [Invariant] -> T.Text
invariants _ [] = ""
invariants i invs =
  definition "invariants" (nextAddrDecl <+> envDecl <+> stateDecl <+> interface i) $ indent 2 . conjuction $ invariantProp <$> invs
  where
    invariantProp :: Invariant -> T.Text
    invariantProp (Invariant _ _ _ (PredTimed p _)) = leanprop p


-- | Definition of invariant claim at constructor poststate
invariantInit :: Constructor -> T.Text
invariantInit (Constructor _ _ i _ _ _ _ _) =
  definition invInitType (invPropDecl i) claim
  where
    claim = indent 2 $ T.unlines
      [ forAll $ envDecl <+> interface i <+> nextAddrDecl <+> stateDecl <+> nextAddrDecl'
      , implication . concat $
        [ [constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar <+> nextAddrVar']
        , [invPropVar <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar]
        ]
      ]

-- | Definition of invariant claim for behaviour cases
invariantStep :: Constructor -> T.Text
invariantStep (Constructor _ _ i _ _ _ _ _) =
  definition invStepType (invPropDecl i) claim
  where
    claim = indent 2 $ T.unlines
      [ forAll $ envDecl <+> interface i <+> nextAddrDecl <+> stateDecl <+> stateDecl' 
      , implication . concat $
        [ [initPrecsType <+> envVar <+> arguments i <+> nextAddrVar ]
        , [stepType <+> stateVar <+> stateVar']
        , [invPropVar <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar]
        , [invPropVar <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar']
        ]
      ]

-- | Lemma extending invariant properties' hold to reachable states,
-- given proof of init and step invariance
invariantReachable :: Constructor -> T.Text
invariantReachable (Constructor _ _ i _ _ _ _ _) =
  lemma invReachType "" claim proof
  where
    claim = indent 2 $ T.unlines
      [ forAll (envDecl <+> interface i <+> nextAddrDecl <+> stateDecl <+> invPropDecl i
        <+> parens ("HIPinvInit :" <+> invInitType <+> invPropVar) <+> parens ("HIPinvStep :" <+> invStepType <+> invPropVar))
      , implication . concat $
        [ [reachableFromInitType <+> envVar <+> arguments i <+> nextAddrVar <+> stateDecl ]
        , [invPropVar <+> envVar <+> arguments i <+> nextAddrVar <+> stateVar]
        ]
      ]
    proof = T.unlines
      [ "  := by"
      , indent 4 $ T.unlines $
        [ "intro" <+> envVar
        , "intros" <+> arguments i
        , "intro" <+> nextAddrVar <+> stateVar <+> invPropVar <+> "HIPinvInit HIPinvStep Hreach"
        , "unfold" <+> reachableFromInitType <+> "at Hreach"
        , "obtain ⟨iState, iNA, Hinit, Hmulti⟩ := Hreach"
        , "obtain ⟨iNA', Hprecs⟩ := Hinit"
        , "apply ActLib.step_multi_step"
        , "  (P := fun s _ =>" <+> invPropVar <+> envVar <+> arguments i <+> nextAddrVar <+> "s)"
        , "  Hmulti"
        , "· apply HIPinvInit"
        , "  assumption"
        , "· intro s s' Hstep _"
        , "  apply HIPinvStep <;> assumption"
        , "· intro x _"
        , "  assumption"
        , "· intro s1 s2 s3 _ Ht2 Ht3"
        , "  exact Ht2 (Ht3 s1)"
        ]
      ]

-- | produce a state value from a list of storage updates
stateval :: Bool -> StorageTyping -> Id -> (Ref LHS -> ValueType -> T.Text) -> [StorageUpdate] -> (T.Text, [([T.Text], T.Text)], Int)
stateval ctor store contract handler updates =
  let (texts, finalI) = runSeq (\(n, (t, _)) -> updateVar store updates handler (SVar nowhere Pre contract n) t) (M.toList store') (if ctor then 1 else 0)
      (vals, bindings) = unzip texts
      bindings' = concat bindings
      finalBindings = if ctor then env1Binding : bindings' else bindings'
      env1Binding = ([iNextAddr 1], "NextAddr1 = NextAddr + 1")
  in
  (T.unwords $ stateConstructor : addr : vals, finalBindings, finalI)
  where
    addr = if ctor then "NextAddr" else parens (stateVar <.> addrField)
    store' = contractStore contract store


contractStore :: Id -> StorageTyping -> Map Id (ValueType, Integer)
contractStore contract store = case M.lookup contract store of
  Just s -> s
  Nothing -> error $ "Internal error: cannot find constructor of " <> contract <> " in store"


-- | Check is an update update a specific storage reference
eqRef :: Ref LHS -> StorageUpdate -> Bool
eqRef r (Update _ r' _) = r == r'

-- | Check if an update updates a location that has a given storage
-- reference as a base
baseRef :: Ref LHS -> StorageUpdate -> Bool
baseRef baseref (Update _ r _) = hasBase r
  where
    hasBase (SVar _ _ _ _) = False
    hasBase (RArrIdx _ r' _ _) = r' == baseref || hasBase r'
    hasBase (RField _ r' _ _) = r' == baseref || hasBase r'

iState :: Int -> T.Text
iState 0 = "STATE"
iState i = "STATE" <> T.pack (show i)

iNextAddr :: Int -> T.Text
iNextAddr 0 = "NextAddr"
iNextAddr i = "NextAddr" <> T.pack (show i)

updateExp :: Exp a -> Fresh (T.Text, [([T.Text],T.Text)])
updateExp (Create _ cid args payment) = do
  let paymentExp = maybe "0" leanexp payment
  (args', argBindings) <- unzip <$> mapM updateExpTyped args
  i <- getIncr
  let bindings = snoc (concat argBindings) ([iState (i+1), iNextAddr (i+1)], T.pack cid <.> constructorType <+> parens ("CallEnv" <+> paymentExp <+> parens (envVar <.> "This") <+> envVar) <+> T.unwords args' <+> iNextAddr i <+> iState (i+1) <+> iNextAddr (i+1))
  pure (iState (i+1), bindings)
updateExp (Address _ c (Create _ cid args payment)) = do
  let paymentExp = maybe "0" leanexp payment
  (args', argBindings) <- unzip <$> mapM updateExpTyped args
  i <- getIncr
  let bindings = snoc (concat argBindings) ([iState (i+1), iNextAddr (i+1)], T.pack cid <.> constructorType <+> parens ("CallEnv" <+> paymentExp <+> parens (envVar <.> "This") <+> envVar) <+> T.unwords args' <+> iNextAddr i <+> iState (i+1) <+> iNextAddr (i+1))
  pure (parens $ iState (i+1) <.> addrField, bindings)
updateExp e = pure (leanexp e, [])

updateExpTyped :: TypedExp -> Fresh (T.Text, [([T.Text], T.Text)])
updateExpTyped (TExp _ te) = updateExp te

unField :: Ref LHS -> Ref LHS -> Ref LHS
unField rFocus (RField pn r cid x) | r == rFocus = SVar pn Pre cid x
unField rFocus (RField pn r cid x) = RField pn (unField rFocus r) cid x
unField _ r' = r'

-- Returns the value of the state after all updates, as well as the relevant let-bindings for said state value
updateVar :: StorageTyping -> [StorageUpdate] -> (Ref LHS -> ValueType -> T.Text) -> Ref LHS -> ValueType -> Fresh (T.Text, [([T.Text], T.Text)])
updateVar store updates handler focus t@(ValueType (TContract cid)) =
  case unsnoc groupedUpdates of
    Nothing -> pure (handler focus t, [])
    Just (_, (firstU@(Update _ _ e) NE.:| [])) | eqRef focus firstU->
      updateExp e
    Just (_, (firstU@(Update _ _ e) NE.:| nextUpdates)) | eqRef focus firstU-> do
      (newState, bindings) <- updateExp e
      (t', bindings') <- unzip <$> traverse (\(n, (t', _)) -> updateVar store nextUpdates (\r _ -> refState newState $ unField focus r) (focus' n) t') (M.toList store')
      pure (parens $ T.unwords $ (T.pack cid <.> stateConstructor) : parens (newState <.> addrField) : t', bindings ++ concat bindings')
    Just (_, fieldUpdates) -> do
      (t', bindings') <- unzip <$> traverse (\(n, (t', _)) -> updateVar store (NE.toList fieldUpdates) handler (focus' n) t') (M.toList store')
      pure (parens $ T.unwords $ (T.pack cid <.> stateConstructor) : parens (refState stateVar focus <.> addrField) : t', concat bindings')
  where
    focus' x = RField nowhere focus cid x
    store' = contractStore cid store

    focusUpdates = filter (\u -> eqRef focus u || baseRef focus u) updates
    groupedUpdates = NE.groupBy (\_ b -> not $ eqRef focus b) focusUpdates

updateVar _ updates handler focus t@(ValueType TAddress) =
  case unsnoc focusUpdates of
    Nothing -> pure (handler focus t, [])
    Just (_, (Update _ _ e)) -> updateExp e
  where
    focusUpdates = filter (\u -> eqRef focus u || baseRef focus u) updates

updateVar _ updates handler focus t@(ValueType (TMapping _ _)) =
  pure (foldl updatedVal (handler focus t) (filter (eqRef focus) updates), [])
    where
      updatedVal _ (Update TByteStr _ _) = error "bytestrings not supported"
      updatedVal _ (Update _ _ e) = mappingExp e 0

updateVar _ updates handler focus t@(ValueType _) =
  pure (foldl updatedVal (handler focus t) (filter (eqRef focus) updates), [])
    where
      updatedVal _ (Update TByteStr _ _) = error "bytestrings not supported"
      updatedVal _ (Update _ _ e) = leanexp e



-- | produce a block of declarations from an interface
interface :: Interface -> T.Text
interface (Interface _ decls) =
  T.unwords $ map decl decls where
  decl (Arg (AbiArg AbiAddressType) name) = parens $ T.pack name <+> ":" <+> abiType AbiAddressType
  decl (Arg (ContractArg _ cid) name) = parens $ T.pack name <+> ":" <+> T.pack cid <.> "State"
  decl (Arg (AbiArg t) name) = parens $ T.pack name <+> ":" <+> abiType t

-- | produce a block of declarations from an interface
interface' :: Interface -> [T.Text]
interface' (Interface _ decls) =
  map decl decls where
  decl (Arg (AbiArg AbiAddressType) name) = parens $ T.pack name <+> ":" <+> abiType AbiAddressType
  decl (Arg (ContractArg _ cid) name) = parens $ T.pack name <+> ":" <+> T.pack cid <.> "State"
  decl (Arg (AbiArg t) name) = parens $ T.pack name <+> ":" <+> abiType t

interfaceType :: Interface -> T.Text
interfaceType (Interface _ []) = ""
interfaceType (Interface _ decls) = (T.pack "→") <+> (
  T.intercalate " → " $ map decl decls)
  where
  decl (Arg (AbiArg AbiAddressType) _) = abiType AbiAddressType
  decl (Arg (ContractArg _ cid) _) = T.pack cid <.> "State"
  decl (Arg (AbiArg t) _) = abiType t

arguments :: Interface -> T.Text
arguments (Interface _ decls) =
  T.unwords $ map (\(Arg _ name) -> T.pack name) decls

-- | lean syntax for a value type
valueType :: ValueType -> T.Text
valueType (ValueType (TContract cid)) = T.pack cid <> "." <> "State"
valueType (ValueType (TMapping k t)) = valueType k <+> "→" <+> valueType t
valueType (ValueType t) = abiType $ toAbiType t

unfoldMappingType :: TValueType AMapping -> ([ValueType], ValueType)
unfoldMappingType mt = go (ValueType mt) []
  where
    go :: ValueType -> [ValueType] -> ([ValueType], ValueType)
    go (ValueType (TMapping key t)) keys = go t (keys ++ [key])
    go t keys = (keys, t)

-- | lean syntax for an abi type
abiType :: AbiType -> T.Text
abiType (AbiUIntType _) = "ℤ"
abiType (AbiIntType _) = "ℤ"
abiType AbiAddressType = "address"
abiType AbiStringType = "String"
abiType a = error $ show a

-- | lean syntax for a return type
returnType :: TypedExp -> T.Text
returnType (TExp (TInteger _ _) _) = "ℤ"
returnType (TExp TUnboundedInt _) = "ℤ"
returnType (TExp TAddress _) = "ℤ"
returnType (TExp TBoolean _) = "Bool"
returnType (TExp (TContract _) _) = error "contracts not allowed as return types"
returnType (TExp (TMapping _ _) _) = error "mappings not supported as return types"
returnType (TExp TByteStr _) = error "bytestrings not supported"
returnType (TExp (TStruct _) _) = error "structs not supported"
returnType (TExp (TArray _ _) _) = error "arrays not supported"


-- | default value for a given type
defaultVal :: ValueType -> T.Text
defaultVal (ValueType (TMapping _ t)) = parens $
  "fun" <+> "_" <+> "=>" <+> defaultVal t
defaultVal (ValueType (TContract _)) = error "Contracts must be explicitly initialized"
defaultVal (ValueType t) = abiVal $ toAbiType t

abiVal :: AbiType -> T.Text
abiVal (AbiUIntType _) = "0"
abiVal (AbiIntType _) = "0"
abiVal AbiAddressType = "0"
abiVal AbiStringType = "\"\""
abiVal _ = error "TODO: missing default values"

-- | lean syntax for an expression
leanexp :: Exp a -> T.Text
-- booleans
leanexp (LitBool _ True)  = "true"
leanexp (LitBool _ False) = "false"
leanexp (And _ e1 e2)  = parens $ leanexp e1  <+> "&&" <+> leanexp e2
leanexp (Or _ e1 e2)   = parens $ leanexp e1  <+> "||" <+> leanexp e2
leanexp (Impl _ e1 e2) = parens $ leanexp e1  <+> "→"  <+> leanexp e2
leanexp (Eq _ _ e1 e2)   = parens $ leanexp e1  <+> "==" <+> leanexp e2
leanexp (NEq _ _ e1 e2)  = parens $ leanexp e1  <+> "≠" <+> leanexp e2
leanexp (Neg _ e)      = parens $ "!" <+> leanexp e
leanexp (LT _ e1 e2)   = parens $ leanexp e1 <+> "<"  <+> leanexp e2
leanexp (LEQ _ e1 e2)  = parens $ leanexp e1 <+> "≤" <+> leanexp e2
leanexp (GT _ e1 e2)   = parens $ leanexp e2 <+> "<"  <+> leanexp e1
leanexp (GEQ _ e1 e2)  = parens $ leanexp e2 <+> "≤" <+> leanexp e1

-- integers
leanexp (LitInt _ i) = T.pack $ show i
leanexp (Add _ e1 e2) = parens $ leanexp e1 <+> "+" <+> leanexp e2
leanexp (Sub _ e1 e2) = parens $ leanexp e1 <+> "-" <+> leanexp e2
leanexp (Mul _ e1 e2) = parens $ leanexp e1 <+> "*" <+> leanexp e2
leanexp (Div _ e1 e2) = parens $ leanexp e1 <+> "/" <+> leanexp e2
leanexp (Mod _ e1 e2) = parens $ leanexp e1 <+> "%" <+> leanexp e2
leanexp (Exp _ e1 e2) = parens $ leanexp e1 <+> "^" <+> leanexp e2
leanexp (IntMin _ n)  = parens $ "INT_MIN"  <+> T.pack (show n)
leanexp (IntMax _ n)  = parens $ "INT_MAX"  <+> T.pack (show n)
leanexp (UIntMin _ n) = parens $ "UINT_MIN" <+> T.pack (show n)
leanexp (UIntMax _ n) = parens $ "UINT_MAX" <+> T.pack (show n)

leanexp (InRange _ t e) = leanexp (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))

-- polymorphic
leanexp (VarRef _ _ r) = ref r
leanexp (ITE _ b e1 e2) = parens $ "if"
                             <+> leanexp b
                             <+> "then"
                             <+> leanexp e1
                             <+> "else"
                             <+> leanexp e2

-- environment values
leanexp (IntEnv _ envVal) = parens $ envVar <.> T.pack (show envVal)
-- Contracts
leanexp Create {} = error "Internal error: leanexp called for creation expression; call updateExp"
leanexp (Address _ c e) = parens $ leanexp e <.> addrField

leanexp me@(Mapping _ _ _ _) = mappingExp me 0
leanexp me@(MappingUpd _ _ _ _ _) = mappingExp me 0

-- unsupported
leanexp Cat {} = error "bytestrings not supported"
leanexp Slice {} = error "bytestrings not supported"
leanexp ByStr {} = error "bytestrings not supported"
leanexp ByLit {} = error "bytestrings not supported"
leanexp ByEnv {} = error "bytestrings not supported"
leanexp Array {} = error "arrays not supported"

mappingExp :: Exp a -> Int -> T.Text
mappingExp (Mapping _ keyType valType@VType es) level = parens $
  "fun" <+> (anon <> (T.pack $ show level)) <+> "=>" <+>
  foldr (mappingElem level keyType) (defaultVal (ValueType valType)) es
mappingExp (MappingUpd _ r keyType _ es) level = parens $
  "fun" <+> (anon <> (T.pack $ show level)) <+> "=>" <+>
  foldr (mappingElem level keyType) (ref r <+> (anon <> (T.pack $ show level))) es
mappingExp e _ = leanexp e

mappingElem :: Int -> TValueType a -> (Exp a, Exp b) -> T.Text -> T.Text
mappingElem level keyType (key, ve) elseText =
  "if" <+> parens (parens (anon <> T.pack (show level)) <+> eqsym keyType <+> leanexp key) <+>
  "then" <+> mappingExp ve (level + 1) <+>
  "else" <+> elseText

eqsym :: TValueType a -> T.Text
eqsym argType = case argType of
  TInteger _ _ -> "=="
  TUnboundedInt -> "=="
  TAddress -> "=="
  TBoolean -> "=="
  TMapping _ _ -> error "mapping as keys not supported"
  TByteStr -> error "bytestrings as keys not supported"
  TArray _ _ -> error "arrays as key not supported"
  TStruct _ -> error "structs as key not supported"
  TContract _ -> error "contracts as key not supported"


-- | lean syntax for a proposition
leanprop :: Exp ABoolean -> T.Text
leanprop (LitBool _ True)  = "True"
leanprop (LitBool _ False) = "False"
leanprop (And _ e1 e2)  = parens $ leanprop e1 <+> "∧" <+> leanprop e2
leanprop (Or _ e1 e2)   = parens $ leanprop e1 <+> "∨" <+> leanprop e2
leanprop (Impl _ e1 e2) = parens $ leanprop e1 <+> "→"  <+> leanprop e2
leanprop (Neg _ e)      = parens $ "¬" <+> leanprop e
leanprop (Eq _ _ e1 e2)   = parens $ leanexp e1 <+> "="  <+> leanexp e2
leanprop (NEq _ _ e1 e2)  = parens $ leanexp e1 <+> "≠" <+> leanexp e2
leanprop (LT _ e1 e2)   = parens $ leanexp e1 <+> "<"  <+> leanexp e2
leanprop (LEQ _ e1 e2)  = parens $ leanexp e1 <+> "≤" <+> leanexp e2
leanprop (GT _ e1 e2)   = parens $ leanexp e1 <+> ">"  <+> leanexp e2
leanprop (GEQ _ e1 e2)  = parens $ leanexp e1 <+> "≥" <+> leanexp e2
leanprop (InRange _ t e) = leanprop (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))
leanprop (ITE _ b e1 e2) =
  parens $ "if" <+> leanbool b <+> "then" <+> leanexp e1 <+> "else" <+> leanexp e2

leanprop e@(VarRef _ _ _) = error "ill formed proposition:" <+> T.pack (show e)

leanbool :: Exp ABoolean -> T.Text
leanbool (LitBool _ True)  = "true"
leanbool (LitBool _ False) = "false"
leanbool (And _ e1 e2)  = parens $ leanbool e1 <+> "&&" <+> leanbool e2
leanbool (Or _ e1 e2)   = parens $ leanbool e1 <+> "||" <+> leanbool e2
leanbool (Impl _ e1 e2) = parens $ leanbool e1 <+> "→" <+> leanbool e2
leanbool (Neg _ e)      = parens $ "!" <+> leanbool e
leanbool (Eq _ t e1 e2)   = leanexp e1 <+> eqsym t <+> leanexp e2
leanbool (NEq _ t e1 e2)  = parens $ "!" <+> parens (leanexp e1 <+> eqsym t <+> leanexp e2)
leanbool (LT _ e1 e2)   = parens $ leanexp e1 <+> "<"  <+> leanexp e2
leanbool (LEQ _ e1 e2)  = parens $ leanexp e1 <+> "≤" <+> leanexp e2
leanbool (GT _ e1 e2)   = parens $ leanexp e1 <+> ">"  <+> leanexp e2
leanbool (GEQ _ e1 e2)  = parens $ leanexp e1 <+> "≥" <+> leanexp e2
leanbool (InRange _ t e) = leanbool (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))

leanbool e = error "ill formed proposition:" <+> T.pack (show e)

-- | lean syntax for a typed expression
typedexp :: TypedExp -> T.Text
typedexp (TExp _ e) = leanexp e

ref :: Ref k -> T.Text
ref (SVar _ Pre cid name) = parens $ stateVar <.> T.pack name
ref (SVar _ Post cid name) = parens $ stateVar' <.> T.pack name
ref (CVar _ _ name) = T.pack name
ref (RArrIdx _ r ix _) = parens $ ref r <+> leanexp ix
ref (RMapIdx _ (TRef _ _ r) ix) = parens $ ref r <+> typedexp ix
ref (RField _ r cid name) = parens $ ref r <.> T.pack name

refState :: T.Text -> Ref k -> T.Text
refState s (SVar _ _ cid name) = parens $ s <.> T.pack name
refState _ (CVar _ _ name) = T.pack name
refState s (RArrIdx _ r ix _) = parens $ refState s r <+> leanexp ix
refState s (RMapIdx _ (TRef _ _ r) ix) = parens $ refState s r <+> typedexp ix
refState s (RField _ r cid name) = parens $ refState s r <.> T.pack name

-- | lean syntax for a list of arguments
leanargs :: [TypedExp] -> T.Text
leanargs es = T.unwords (map typedexp es)

fresh :: Id -> Fresh T.Text
fresh name = state $ \s -> (T.pack (name <> show s), s + 1)

freshId :: Id -> Fresh Id
freshId name = state $ \s -> (name <> show s, s + 1)

getIncr :: Fresh Int
getIncr = state $ \s -> (s, s + 1)

evalSeq :: Traversable t => (a -> Fresh b) -> t a -> t b
evalSeq f xs = evalState (sequence (f <$> xs)) 0

runSeq :: Traversable t => (a -> Fresh b) -> t a -> Int -> (t b, Int)
runSeq f xs iInit = runState (sequence (f <$> xs)) iInit

--- text manipulation ---

definition :: T.Text -> T.Text -> T.Text -> T.Text
definition name args value = T.unlines
  [ "def" <+> name <+> args <+> ":="
  , value
  ]

inductive :: T.Text -> T.Text -> T.Text -> [(T.Text, T.Text, T.Text)] -> T.Text
inductive name args indices constructors = T.unlines
  [ "inductive" <+> name <+> args <+> ":" <+> indices <+> "where"
  , T.unlines (((<>) "| " . uncurry3 inductiveConstructor) <$> constructors)
  ]

inductiveConstructor :: T.Text -> T.Text -> T.Text -> T.Text
inductiveConstructor ctorName bindings body =
     ctorName <+> ":" <+> bindings <> "\n" <> body

lemma :: T.Text -> T.Text -> T.Text -> T.Text -> T.Text
lemma name args claim proof = T.unlines
  [ "theorem" <+> name <+> args <+> ":"
  , claim
  , proof
  ]


-- | forall bindings
forAll :: T.Text -> T.Text
forAll bindings = "∀" <+> bindings <> ","

-- | multiline implication
implication :: [T.Text] -> T.Text
implication xs = "   " <> T.intercalate "\n→ " xs

-- | multiline implication
namedHyps :: [(T.Text, T.Text)] -> T.Text
namedHyps xs = T.intercalate "\n" (go <$> xs)
  where go (n, h) = parens( " H_" <> n <> " : " <> h <> " ")

-- | multiline conjuction
conjuction :: [T.Text] -> T.Text
conjuction [] = "   True"
conjuction xs = "   " <> T.intercalate "\n∧ " xs

-- | wrap text in parentheses
parens :: T.Text -> T.Text
parens s = "(" <> s <> ")"

tuple :: T.Text -> T.Text -> T.Text
tuple a b = "(" <> a <> ", " <> b <> ")"

indent :: Int -> T.Text -> T.Text
indent n = T.unlines . fmap (T.replicate n " " <>) . T.lines

(<+>) :: T.Text -> T.Text -> T.Text
"" <+> t2 = t2
t1 <+> "" = t1
t1 <+> t2 = t1 <> " " <> t2

(<.>) :: T.Text -> T.Text -> T.Text
t1 <.> t2 = t1 <> "." <> t2

--- constants ---

stateType :: T.Text
stateType = "State"

stateVar :: T.Text
stateVar = "STATE"

stateVar' :: T.Text
stateVar' = "STATE'"

nextVar :: T.Text
nextVar = "NEXT"

stateDecl :: T.Text
stateDecl = parens $ stateVar <+> ":" <+> stateType

stateDecl' :: T.Text
stateDecl' = parens $ stateVar' <+> ":" <+> stateType

stateConstructor :: T.Text
stateConstructor = stateType <.> "mk"

addressType :: T.Text
addressType = "address"

addrField :: T.Text
addrField = "addr"

addrFieldDecl :: T.Text
addrFieldDecl = addrField <> " : address"

returnSuffix :: T.Text
returnSuffix = "_ret"

postSuffix :: T.Text
postSuffix = "_post"

constructorType :: T.Text
constructorType = "constructor"

invInitType :: T.Text
invInitType  = "invariantInit"

invStepType :: T.Text
invStepType  = "invariantStep"

invReachType :: T.Text
invReachType  = "invariantReachable"

baseSuffix :: T.Text
baseSuffix = "_base"

stepSuffix :: T.Text
stepSuffix = "_step"

introSuffix :: T.Text
introSuffix = "_intro"

caseSuffix :: Int -> T.Text
caseSuffix i = "_case" <> T.pack (show i)

localStepType :: Id -> T.Text
localStepType name = T.pack name <> "_transition"

stepType :: T.Text
stepType = "step"

stepBeforeType :: T.Text
stepBeforeType = "stepBefore"

extStepType :: T.Text
extStepType = "transition"

addressInType :: T.Text
addressInType = "addressIn"

contractAddressInType :: T.Text
contractAddressInType = "addressIn"

noAliasingType :: T.Text
noAliasingType = "noAliasing"

nextAddrConstraintType :: T.Text
nextAddrConstraintType = "nextAddrConstraint"

initStateType :: T.Text
initStateType = "init"

initStateBeforeType :: T.Text
initStateBeforeType = "initBefore"

invPropVar :: T.Text
invPropVar = "IP"

invPropType :: Interface -> T.Text
invPropType (Interface _ decls) = T.intercalate " → " $ concat [[envType], map decl' decls, [addressType, stateType, "Prop"]]
  where
  decl' (Arg (ContractArg _ cid) _) = T.pack cid <> ".State"
  decl' (Arg (AbiArg t) _) = abiType t

invPropDecl :: Interface -> T.Text
invPropDecl i = parens $ invPropVar <+> ":" <+> invPropType i

initPrecsType :: T.Text
initPrecsType = "constructor_conds"

behvPrecsType :: T.Text
behvPrecsType = "behvPrecs"

integerBoundsType :: T.Text
integerBoundsType = "stateIntegerBounds"

multistepType :: T.Text
multistepType = "multistep"

multistepBeforeType :: T.Text
multistepBeforeType = "multistepBefore"

reachableType :: T.Text
reachableType = "reachable"

reachableBeforeType :: T.Text
reachableBeforeType = "reachableBefore"

reachableFromInitType :: T.Text
reachableFromInitType = "reachableFromInit"

reachStep:: T.Text
reachStep= "reach_step"

nextAddrType :: T.Text
nextAddrType = "address"

nextAddrVar :: T.Text
nextAddrVar = "NextAddr"

nextAddrDecl :: T.Text
nextAddrDecl = parens $ nextAddrVar <+> ":" <+> nextAddrType

nextAddrVar' :: T.Text
nextAddrVar' = "NextAddr'"

nextAddrDecl' :: T.Text
nextAddrDecl' = parens $ nextAddrVar' <+> ":" <+> nextAddrType

envType :: T.Text
envType = "Env"

envVar :: T.Text
envVar = "ENV"

envVar' :: T.Text
envVar' = "ENV'"

envDecl :: T.Text
envDecl = parens $ envVar <+> ":" <+> envType

envDecl' :: T.Text
envDecl' = parens $ envVar' <+> ":" <+> envType

boundType :: T.Text
boundType = "address"

boundVar :: T.Text
boundVar = "BOUND"

boundDecl :: T.Text
boundDecl = parens $ boundVar <+> ":" <+> boundType

anon :: T.Text
anon = "_binding_"
