(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module A.

Record State : Set := state
{ f : address -> Z
; x : Z
}.

Definition A (ENV : Env)  :=
state (fun _binding_0 => ((fun _ => 0) _binding_0)) 0
.

Inductive reachable  : State -> State -> Prop :=
| A_base : forall (ENV : Env) ,
     reachable (A ENV ) (A ENV )

.

End A.


Module B.

Record State : Set := state
{ a : A.State
; x : Z
}.

Definition B (ENV : Env) (u : Z) :=
state (A.A ENV ) u
.

Definition setx0 (ENV : Env) (STATE : State) (z : Z) :=
state (A.state (fun _binding_0 => ((A.f (a STATE)) _binding_0)) z) (x STATE)
.

Definition setf0 (ENV : Env) (STATE : State) (i : address) :=
state (A.state (fun _binding_0 => if ((_binding_0 =? i))%bool then 1 else ((A.f (a STATE)) _binding_0)) (A.x (a STATE))) (x STATE)
.

Inductive reachable  : State -> State -> Prop :=
| B_base : forall (ENV : Env) (u : Z),
     ((0 <= u) /\ (u <= (UINT_MAX 256)))
  -> reachable (B ENV u) (B ENV u)

| setx0_step : forall (ENV : Env) (BASE STATE : State) (z : Z),
     reachable BASE STATE
  -> True
  -> ((0 <= z) /\ (z <= (UINT_MAX 256)))
  -> ((0 <= (A.x (a STATE))) /\ ((A.x (a STATE)) <= (UINT_MAX 256)))
  -> reachable BASE (setx0 ENV STATE z)

| setf0_step : forall (ENV : Env) (BASE STATE : State) (i : address),
     reachable BASE STATE
  -> True
  -> ((0 <= i) /\ (i <= (UINT_MAX 160)))
  -> ((0 <= ((A.f (a STATE)) i)) /\ (((A.f (a STATE)) i) <= (UINT_MAX 256)))
  -> reachable BASE (setf0 ENV STATE i)

.

End B.


Module C.

Record State : Set := state
{ b : B.State
; w : Z
}.

Definition C (ENV : Env)  :=
state (B.B ENV 42) 0
.

Definition setf0 (ENV : Env) (STATE : State) (i : address) :=
state (B.state (A.state (fun _binding_0 => if ((_binding_0 =? i))%bool then 2 else ((A.f (B.a (b STATE))) _binding_0)) (A.x (B.a (b STATE)))) (B.x (b STATE))) (w STATE)
.

Definition setxw0 (ENV : Env) (STATE : State) (i : address) :=
state (B.state (A.state (fun _binding_0 => ((A.f (B.a (b STATE))) _binding_0)) 1) 1) (w STATE)
.

Inductive reachable  : State -> State -> Prop :=
| C_base : forall (ENV : Env) ,
     reachable (C ENV ) (C ENV )

| setf0_step : forall (ENV : Env) (BASE STATE : State) (i : address),
     reachable BASE STATE
  -> True
  -> ((0 <= i) /\ (i <= (UINT_MAX 160)))
  -> ((0 <= ((A.f (B.a (b STATE))) i)) /\ (((A.f (B.a (b STATE))) i) <= (UINT_MAX 256)))
  -> reachable BASE (setf0 ENV STATE i)

| setxw0_step : forall (ENV : Env) (BASE STATE : State) (i : address),
     reachable BASE STATE
  -> True
  -> ((0 <= i) /\ (i <= (UINT_MAX 160)))
  -> ((0 <= (A.x (B.a (b STATE)))) /\ ((A.x (B.a (b STATE))) <= (UINT_MAX 256)))
  -> ((0 <= (B.x (b STATE))) /\ ((B.x (b STATE)) <= (UINT_MAX 256)))
  -> reachable BASE (setxw0 ENV STATE i)

.

End C.
