(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module Token.

Record State : Set := state
{ balances : address -> Z
}.

Definition Token (ENV : Env) (a : address) (amt : Z) :=
state (fun _binding_0 => if ((_binding_0 =? a))%bool then amt else ((fun _ => 0) _binding_0))
.

Definition transfer0 (ENV : Env) (STATE : State) (to : address) (amt : Z) :=
state (fun _binding_0 => if ((_binding_0 =? to))%bool then (((balances STATE) to) + amt) else if ((_binding_0 =? (Caller ENV)))%bool then (((balances STATE) (Caller ENV)) - amt) else ((balances STATE) _binding_0))
.

Definition transfer1 (ENV : Env) (STATE : State) (to : address) (amt : Z) :=
state (fun _binding_0 => ((balances STATE) _binding_0))
.

Inductive transfer0_ret (ENV : Env) (STATE : State) (to : address) (amt : Z) : Z -> Prop :=
| transfer0_ret_intro :
     (amt <= ((balances STATE) (Caller ENV)))
  -> ((0 <= (((balances STATE) to) + amt)) /\ ((((balances STATE) to) + amt) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) <> to)
  -> transfer0_ret ENV STATE to amt 1

.

Inductive transfer1_ret (ENV : Env) (STATE : State) (to : address) (amt : Z) : Z -> Prop :=
| transfer1_ret_intro :
     (amt <= ((balances STATE) (Caller ENV)))
  -> ((0 <= (((balances STATE) to) + amt)) /\ ((((balances STATE) to) + amt) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> ((Caller ENV) = to)
  -> transfer1_ret ENV STATE to amt 1

.

Inductive reachable  : State -> State -> Prop :=
| Token_base : forall (ENV : Env) (a : address) (amt : Z),
     ((0 <= a) /\ (a <= (UINT_MAX 160)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> reachable (Token ENV a amt) (Token ENV a amt)

| transfer0_step : forall (ENV : Env) (BASE STATE : State) (to : address) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) <> to)
  -> (amt <= ((balances STATE) (Caller ENV)))
  -> ((0 <= (((balances STATE) to) + amt)) /\ ((((balances STATE) to) + amt) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable BASE (transfer0 ENV STATE to amt)

| transfer1_step : forall (ENV : Env) (BASE STATE : State) (to : address) (amt : Z),
     reachable BASE STATE
  -> ((Caller ENV) = to)
  -> (amt <= ((balances STATE) (Caller ENV)))
  -> ((0 <= (((balances STATE) to) + amt)) /\ ((((balances STATE) to) + amt) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= to) /\ (to <= (UINT_MAX 160)))
  -> ((0 <= amt) /\ (amt <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) (Caller ENV))) /\ (((balances STATE) (Caller ENV)) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= ((balances STATE) to)) /\ (((balances STATE) to) <= (UINT_MAX 256)))
  -> ((0 <= (Caller ENV)) /\ ((Caller ENV) <= (UINT_MAX 160)))
  -> reachable BASE (transfer1 ENV STATE to amt)

.

End Token.
