(* --- GENERATED BY ACT --- *)

Require Import Coq.ZArith.ZArith.
Require Import ActLib.ActLib.
Require Coq.Strings.String.

Module Str := Coq.Strings.String.
Open Scope Z_scope.

Module StateMachine.

Record State : Set := state
{ x : Z
}.

Definition StateMachine (ENV : Env)  :=
state 0
.

Definition f0 (ENV : Env) (STATE : State)  :=
state 1
.

Definition g0 (ENV : Env) (STATE : State)  :=
state 2
.

Definition h0 (ENV : Env) (STATE : State)  :=
state 0
.

Inductive reachable  : State -> State -> Prop :=
| StateMachine_base : forall (ENV : Env) ,
     reachable (StateMachine ENV ) (StateMachine ENV )

| f0_step : forall (ENV : Env) (BASE STATE : State) ,
     reachable BASE STATE
  -> True
  -> ((x STATE) = 0)
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> reachable BASE (f0 ENV STATE )

| g0_step : forall (ENV : Env) (BASE STATE : State) ,
     reachable BASE STATE
  -> True
  -> ((x STATE) = 1)
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> reachable BASE (g0 ENV STATE )

| h0_step : forall (ENV : Env) (BASE STATE : State) ,
     reachable BASE STATE
  -> True
  -> ((x STATE) = 2)
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> ((0 <= (x STATE)) /\ ((x STATE) <= (UINT_MAX 256)))
  -> reachable BASE (h0 ENV STATE )

.

End StateMachine.
